var $sfTabs=null;
define("starfield/sf.tabs",["jq!starfield/jquery.mod","foscss!starfield/sf.core.css"],function(){return function(c){c.fn.sfTabs=function(f,d){var e=c(this),j=e.data("tabs-id");if(j==null||j.length==0)j="sfTabs"+Math.round(Math.random()*65535),e.data("tabs-id",j);var g=c.fn.sfTabs.instances[j];if(g!=null)return g.me_this=this,g.me=e,g.fn(g,f,d);g=c.fn.sfTabs.instances[j]={me_this:this,me:c(this),initialized:!1,fn:function(b,d,a){function f(a){b.meId=b.me.data("tabs-id");b.settings=typeof b.settings==
"undefined"?c.extend(!0,{context:self,tabControlContext:self,bborder:!1,ignoreRedundantCallbacks:!0,mode:"classic",onTabSelected:null,onTabDeselected:null},a):c.extend(!0,b.settings,a);b.context=$sf.util.context(b.settings.tabControlContext,b.settings.context);if(b.initialized!=!0)b.tabs=null,b.tabLastSelected=null,b.tabsHeight=0;if(b.tabs!=null)c("*",b.tabs).unbind(),b.tabs.remove(),b.tabs=null,b.tabsHeight=0;b.wrapper&&b.wrapper.remove();var d,a=b.me.children(".sf-tabs-content");if(a.length!=0&&
(d=null,d=d=b.me.children(".sf-tabs,.sf-g-tabs,.sf-tabs-wiz,.sf-tabs-toggle"),!(d.length>0))){b.tabs=c("<ul/>").addClass("sf-tabs-menu");b.wrapper=b.wizard=b.toggle=null;switch(b.settings.mode){case "wizard":b.tabs.addClass("sf-tabs-wiz-list");b.wrapper=b.wizard=c("<div class='sf-tabs-wiz' />").append(b.tabs);break;case "toggle":b.tabs.addClass("sf-tabs-toggle-list");b.wrapper=b.toggle=c("<div class='sf-tabs-toggle' />").append(b.tabs);break;default:b.tabs.addClass($sf.skin=="fos"?"sf-g-tabs":"sf-tabs"),
b.settings.bborder===!0&&b.tabs.addClass($sf.skin=="fos"?"sf-g-tabs-bborder":"sf-tabs-bborder")}var h=a.filter(".sf-tabs-actv-content").length>0,e=!1;for(d=0;d<a.length;d++){var g=c(a[d]),y=c("<li />"),B=g.attr("data-icon-class"),C=c('<a href="#" onclick="return false" />').appendTo(y),m=null;B?(m=c("<span/>").addClass(B),C.append(m).append(g.attr("data-title"))):(b.wizard?m=c("<span/>").addClass("sf-tabs-wiz-txt").append(g.attr("data-title")):b.toggle?m=c("<span/>").addClass("sf-tabs-toggle-txt").append(g.attr("data-title")):
C.append(g.attr("data-title")),m&&C.append(m));B=g.is(".sf-tabs-hidden");B==!0&&y.addClass("sf-tabs-hidden").hide();if(g.is(".sf-tabs-actv-content")==!0||h==!1&&B==!1){e=h=!0;b.wizard?y.addClass("sf-tabs-wiz-step-current"):b.toggle?y.addClass("sf-tabs-toggle-actv"):y.addClass("sf-tabs-actv-tab sf-g-tab-active");g.addClass("sf-tabs-actv-content").show();b.wizard?y.addClass("sf-tabs-wiz-step-current"):b.toggle&&y.addClass("sf-tabs-toggle-actv");if((b.settings.ignoreRedundantCallbacks==!1||b.tabLastSelected!=
null&&g[0]!=b.tabLastSelected)&&c.isFunction(b.settings.onTabSelected)==!0)b.settings.onTabSelected(b.me,d,g);b.tabLastSelected=g[0]}else b.wizard&&y.addClass(e?"sf-tabs-wiz-step-incomplete":"sf-tabs-wiz-step-complete"),g.hide();b.tabs.append(y);y.bind("click",q)}b.wizard?b.tabs.children("li:last").children("a").addClass("sf-tabs-wiz-list-last"):b.toggle&&b.tabs.children("li:last").addClass("sf-tabs-toggle-list-last");a=b.context.isSingle()?b.me:b.context.ext.iframe();a.parent().length==0?a.prepend(b.wrapper?
b.wrapper:b.tabs):a.before(b.wrapper?b.wrapper:b.tabs);u();b.tabsHeight=b.tabs.outerHeight()}if(b.initialized==!1)b.initialized=!0}function g(a){if(b.tabs==null)return null;var d=b.tabs.find("li");if(a<0||a>=d.length)return null;d=c(d[a]);return b.me.children(".sf-tabs-content:eq("+a+")").length==0?null:d.is(".sf-tabs-disabled-tab")}function j(a){if(b.tabs!=null){var d=b.tabs.find("li");a<0||a>=d.length||(d=c(d[a]),b.me.children(".sf-tabs-content:eq("+a+")").length!=0&&d.removeClass("sf-tabs-disabled-tab"))}}
function z(a){if(b.tabs!=null){var d=b.tabs.find("li");a<0||a>=d.length||(d=c(d[a]),b.me.children(".sf-tabs-content:eq("+a+")").length!=0&&d.addClass("sf-tabs-disabled-tab"))}}function q(){c(document.body).trigger("click",{target:this,sourcetype:"tab"});if(b.tabs==null)return!1;var a=c(this).closest("li");if(a.length==0||a.is(".sf-tabs-actv-tab")||a.is(".sf-g-tab-active")||a.is(".sf-tabs-wiz-step-current")||a.is(".sf-tabs-toggle-step-current")||a.is(".sf-tabs-wiz-step-incomplete"))return!1;var d=
b.tabs.find("li"),a=c.inArray(a[0],d);if(a<0)return!1;if(b.me.children(".sf-tabs-content:eq("+a+")").length==0)return!1;A(a);return!1}function r(){var a=b.me.children(".sf-tabs-content"),d=a.filter(".sf-tabs-actv-content");return a.length==0||d.length==0?-1:c.inArray(d[0],a)}function A(a){if(b.tabs!=null){var d=b.tabs.find("li");if(!(a<0||a>=d.length)){var f=c(d[a]),h=b.me.children(".sf-tabs-content:eq("+a+")");if(h.length!=0&&f.is(".sf-tabs-disabled-tab")!=!0){if(c.isFunction(b.settings.onTabSelected)==
!0&&b.settings.onTabSelected(b.me,a,h)==!1)return!1;var e;d.removeClass("sf-tabs-actv-tab sf-g-tab-active sf-tabs-wiz-step-current sf-tabs-toggle-actv sf-tabs-wiz-step-incomplete sf-tabs-wiz-step-complete");if(b.wizard){for(e=0;e<a;e++)c(d[e]).addClass("sf-tabs-wiz-step-complete");for(e=a+1;e<d.length;e++)c(d[e]).addClass("sf-tabs-wiz-step-incomplete");f.addClass("sf-tabs-wiz-step-current")}else b.toggle?f.addClass("sf-tabs-toggle-actv"):f.addClass("sf-tabs-actv-tab sf-g-tab-active");f.show();b.me.children(".sf-tabs-content").not(h).each(function(a,
d){var f=c(d);if(c.isFunction(b.settings.onTabDeselected)==!0){var h=c.inArray(f,b.me.children(".sf-tabs-content"));b.settings.onTabDeselected(b.me,h,f)}}).removeClass("sf-tabs-actv-content").hide();h.addClass("sf-tabs-actv-content").show()}}}}function p(a){if(b.tabs==null)return null;var d=b.tabs.find("li");if(a<0||a>=d.length)return null;d=c(d[a]);return b.me.children(".sf-tabs-content:eq("+a+")").length==0?null:!d.is(":hidden")}function s(a){if(b.tabs!=null){var d=b.tabs.find("li");if(!(a<0||a>=
d.length)){var f=c(d[a]),h=b.me.children(".sf-tabs-content:eq("+a+")");if(h.length!=0&&(f.addClass("sf-tabs-hidden").hide(),h.addClass("sf-tabs-hidden").hide(),r()==a)){b.me.children(".sf-tabs-content").removeClass("sf-tabs-actv-content").hide();for(f=0;f<d.length;f++)if(f!=a&&p(f)==!0){A(f);break}}}}}function h(a){if(b.tabs!=null){var d=b.tabs.find("li");if(!(a<0||a>=d.length)){var d=c(d[a]),f=b.me.children(".sf-tabs-content:eq("+a+")");f.length!=0&&(d.removeClass("sf-tabs-hidden").show(),f.removeClass("sf-tabs-hidden"),
r()==-1&&A(a))}}}function u(a){if(b.tabs!=null){var d=b.tabs.find("li");if(typeof a!=="number")for(a=0;a<d.length;a++){var f=c(d[a]),h=b.me.children(".sf-tabs-content:eq("+a+")");h.length!=0&&o(f,h.attr("data-class"))}else a>=0&&a<d.length&&(f=c(d[a]),h=b.me.children(".sf-tabs-content:eq("+a+")"),h.length!=0&&o(f,h.attr("data-class")))}}function o(a,b){if(a&&!(a.length===0||typeof b!=="string")){for(var d=(a.attr("class")||"").split(" "),c=[],f=0;f<d.length;f++){var y=d[f];(/sf\-tabs[a-z0-9\_\.\-]*/i.test(y)||
/sf\-g\-tab[a-z0-9\_\.\-]*/i.test(y))&&c.push(y)}d=c.join(" ")+" "+b;a.attr("class",d)}}if(e.length==0)return e;b.logger=$sf.util.logger(e.attr("id")).log;if(typeof d=="string")switch(d.toLowerCase()){case "isinitialized":return b.initialized;case "destroy":if(b.initialized!=!1){if(b.tabs!=null)c("*",b.tabs).unbind(),b.tabs.remove(),b.wrapper&&b.wrapper.remove(),b.tabs=b.wrapper=null,b.tabsHeight=0,b.tabLastSelected=null;b.me.children(".sf-tabs-content").show();b.initialized=!1;delete b.settings}break;
case "isdisabled":return g(a);case "disable":z(a);break;case "enable":j(a);break;case "getselected":return r(a);case "select":A(a);break;case "isvisible":return p(a);case "hide":s(a);break;case "show":h(a);break;case "updateTab":u(a);break;default:f(a)}else f(d);return b.me}};return g.fn(g,f,d)};c.fn.sfTabs.instances={};c.fn.sfTabs.globals={};return c.fn.sfTabs}($sf.getjQuery())});
define("starfield/sf.growl",["i18n!starfield/sf.i18n/duel","css!starfield/sf.core.css","jq!starfield/jquery.mod"],function(c){return function(f){f.fn.sfGrowl=function(d){function e(){a.slideUp(500,j)}function j(){m.unbind();g.unbind();g.remove();b.children().length<3&&k.hide();b.children().length==1&&(b.unbind(),b.remove())}d=f.extend({icon:"",title:"",content:"",location:{},fadetime:0,width:null,onClose:null},d);if(typeof d.title_text=="string")d.title=d.title_text;if(typeof d.paragraph_html=="string")d.content=
d.paragraph_html;d.fadeTimer=null;var g=f(this);g.addClass("sf_growl");var b;b=f("#sf_growl");b.length<1&&(b=f(document.createElement("div")).attr("id","sf_growl"),$sf.util.ua.ie6&&b.css("position","absolute"),typeof d.location.top!="undefined"&&b.css("top",d.location.top+"px"),typeof d.location.right!="undefined"&&b.css("right",d.location.right+"px"),typeof d.location.bottom!="undefined"&&b.css("bottom",d.location.bottom+"px"),typeof d.location.left!="undefined"&&b.css("left",d.location.left+"px"),
f("body").append(b));d.width!=null&&b.css("width",d.width);var k=f("#sf_growl_close_all",b);k.length<1&&(k=f(document.createElement("div")).attr("id","sf_growl_close_all").html("[ "+c["sf.growl"].closeAll+" ]"),b.prepend(k));k.bind("click.sf_growl_close_all",function(){f(".sf_growl_bg",b).slideUp(500,j)});var a=f(document.createElement("div")).addClass("sf_growl_bg"),m=f(document.createElement("a")).addClass("sf_growl_close").addClass("sf_growl_sprite").bind("click.sf_growl",function(){if(f.isFunction(d.onClose)==
!0&&!d.onClose(g))return!1;e();return!1});a.append(m);var l=null;if(d.title!=""){d.icon.length>0&&(l=f(document.createElement("div")).addClass("sf_growl_ico").addClass("sf_growl_sprite").addClass("sf_growl_ico_"+d.icon));var w=f(document.createElement("div")).addClass("sf_growl_title").html(d.title)}var z=f(document.createElement("div")).addClass("sf_growl_msg");l!=null&&z.append(l);z.append(w);l=f(document.createElement("div")).addClass("sf_growl_content").html(d.content);z.append(l);a.append(z);
g.append(a.hide());b.append(g);a.fadeIn(600);b.children().length>2&&k.css({display:"block"});if(d.fadetime>0)d.fadeTimer=window.setTimeout(e,d.fadetime);g.bind("mouseenter.sf_growl",function(){if(d.fadeTimer!=null)clearTimeout(d.fadeTimer),d.fadeTimer=null})};return f.fn.sfGrowl}($sf.getjQuery())});
define("starfield/sf.tipper",["i18n!starfield/sf.i18n/duel","css!starfield/sf.core.css","starfield/sf.util","jq!starfield/jquery.mod"],function(c){return function(f){function d(d,c){var g=d;g.is(".sf_tipper,.sf-tip")==!1&&(g=f(".sf_tipper,.sf-tip",d));g.each(function(){var b=f(this),d=b.attr("data-title");if(typeof d!="string"||d.length==0)d=b.attr("data-tipper-title");var a=b.attr("data-content");if(typeof a!="string"||a.length==0)a=b.attr("data-tipper-content");var e=b.attr("data-style");if(typeof e!=
"string"||e.length==0)e=b.attr("data-tipper-style");var g=b.attr("data-location");if(typeof g!="string"||g.length==0)g=b.attr("data-tipper-location");var w=b.attr("data-width");if(typeof w!="string"||w.length==0)w=b.attr("data-tipper-width");var z=b.attr("data-target");if(typeof z!="string"||z.length==0)z=b.attr("data-tipper-target");z=typeof z!="string"||z.length==0?void 0:f(z);b.sfTipper(c,{style:e,location:g,title:d,content:a,width:w,target:z,initOnly:!0})})}f.fn.sfTipper=function(e,j){var g=f.extend({wireup:!1},
e),b=f(this);if(g.wireup===!0)return delete e.wireup,d(b,e),b;var k=b.data("sf-tipper-id");if(!k||k.length==0)k=Math.round(Math.random()*1E6),b.data("sf-tipper-id",k);g=f.fn.sfTipper.instances[k];if(g!=null)return g.me=b,g.fn(g,e,j);g=f.fn.sfTipper.instances[k]={me:b,meId:k,init:!1,settings:null,fn:function(a,d,e){function g(){t||f("iframe",o.document).each(function(){this.contentWindow===u&&(t=f(this))});return t}function j(){var a=f(o).scrollLeft(),b=f(o).scrollTop();return{left:a,top:b,right:a+
f(o).width(),bottom:b+f(o).height()}}function q(){return h.style=="tooltip"?"tipper":h.style}function r(){h.resize=!0;n[h.style].positionIt(n[h.style].getElements(b))}function A(a){var d=f(a.target);h.resize=!0;n[h.style].positionIt(n[h.style].getElements(b));var c=d.offset().top,d=c+d.height(),e=b.offset().top;(e<=c||e>=d)&&s(a)}function p(a,d){var c=a.indexOf("<\!--more--\>");if(c>-1){var e=a.substring(0,c),c=a.substring(c+11),a=e+'<div class="sf-tipper-more" style="display:none;">'+c+'</div><div class="sf-tipper-morelink"><a href="javascript: void(0);" onclick="return false;">'+
h.showMoreText+"</a></div>";c.indexOf("sf-tourpoint-nav")>-1&&(e=f("<div>"+a+"</div>"),e.find(".sf-tourpoint-nav").insertAfter(e.find(".sf-tipper-morelink")),a=e.html())}d.html(a);d.find(".sf-tipper-morelink a").bind("click",function(){var a=f(this),c=d.find(".sf-tipper-more");c.length>0&&(c.is(":visible")?(c.hide(),a.text(h.showMoreText)):(c.show(),a.text(h.showLessText)),a=q(),n[a].positionIt(n[a].getElements(b)))})}function s(a){var d=!1;if(a&&a.target)if(a=f(a.target),a.is(".sf-tipper-close")===
!1&&a.closest(".sf-"+q()).length>0&&a.is("a")===!1)if(a.is(".sf-tourpoint-nav-item"))return!1;else if(a.parent(".sf-tourpoint-nav").length>0)d=!0;else return!1;else if(a.is("a")&&a.parent().is(".sf-tipper-morelink"))return!0;if(f.isFunction(h.onClose)==!0&&!h.onClose(b))return!1;x.fadeTipper(void 0,void 0,d);return!0}$sf.util.logger(k.toString(),"duel");var h=f.extend({style:"tooltip",title:"",content:"",location:"auto",close:!1,closeTippers:void 0,initOnly:!1,onClose:null,onOpen:null,onDisplay:null,
autoOpen:!1,context:self,displayContext:self,width:void 0,disableClose:!1,disableFade:!1,attachIcon:!0,wireup:!1,zIndex:null,suppress:!1,suppressTippers:void 0,resume:!1,resumeTippers:void 0,destroy:!1,destroyTippers:void 0,target:void 0,showMoreText:c["sf.tipper"].more,showLessText:c["sf.tipper"].less},a.settings,d,e);a.settings=h;a.defaultWidths={qt:180,tooltip:213,tourpoint:213,howl:400};var u=h.context,o=h.displayContext,t=null,n={tooltip:{build:function(){return n.tipbox.build("tipper")},getElements:function(a){return n.tipbox.getElements(a)},
positionIt:function(a){return n.tipbox.positionIt(a)}},tourpoint:{build:function(){return n.tipbox.build("tourpoint")},getElements:function(a){return n.tipbox.getElements(a)},positionIt:function(a){return n.tipbox.positionIt(a)}},tipbox:{build:function(d){var c=f(o.document.createElement("div")).data("sf-tipper",b.data("sf-tipper")).data("sf-tipper-target",b).attr("class","sf-"+d).attr("data-style",d);h.groupId&&c.attr("data-group",h.groupId);h.zIndex&&c.css("z-index",h.zIndex);a.outside=c;f("body:first",
o.document).append(c);c.data("OnResize",r);c.data("OnScroll",A);c.data("OnClose",s);var e=f("<div class='sf-tipper-close sf-icn-close2 sf-icn' />"),g=parseInt(h.width),g=isNaN(g)||g===0?a.defaultWidths[d]:g,g=f("<div class='sf-"+d+"-wrap' />").css("width",g+"px");a.master=g;h.disableClose==!1&&g.append(e);c.append(g);e=f("<div class='sf-"+d+"-body' />");g.append(e);if(d=="tourpoint"&&h.heading){var j=f("<div class='sf-"+d+"-titlebarheading' />");e.append(j);a.heading=j;j.html(h.heading)}else a.heading=
null;h.title?(j=f("<h6 class='sf-"+d+"-heading' />"),e.append(j),a.title=j,j.html(h.title)):a.title=null;if(h.content)j=f("<div class='sf-"+d+"-content' />"),e.append(j),a.content=j,p(h.content,j);e=f(document.createElement("div"));a.arrow=e;d==="howl"&&e.addClass("sf-"+d+"-arrow-wrap");c.append(e);return{container:c,masterContainer:g,arrowDiv:e}},getElements:function(){return{container:a.outside,masterContainer:a.master,arrowDiv:a.arrow}},positionIt:function(a){var d=typeof h.target==="undefined"?
b:h.target;d.position();d=d.offset();if(o!==u){var c=g().offset();d.left+=c.left;d.top+=c.top}var c=a.masterContainer.outerWidth(),f=a.masterContainer.outerHeight(),e=j(),k=h.location;h.location=="auto"&&(k=d.top+f+10<e.bottom?"bottom":"top",k+=d.left+c+25<e.right?"right":"left");var e=k.indexOf("left")>-1?-1:1,l=k.indexOf("top")>-1?-1:1,m=q();a.arrowDiv.attr("class","sf-"+m+"-ptr-"+k+" sf-"+m+"-ptr");a.masterContainer.css({"float":e<0?"left":"right"});a.container.css({left:(e<0?d.left-c-a.arrowDiv.width()-
2:d.left+b.outerWidth()+2)+"px",top:d.top+((l<0?f:0)+b.height()/2)*l+"px",width:c+a.arrowDiv.width()-1+"px"})}},qt:{buildContainer:function(){return n.bubble.build("qt")},getElements:function(a){return n.bubble.getElements(a)},load:function(a,b){return n.bubble.load("qt",a,b)},positionIt:function(a){return n.bubble.positionIt(a,"qt",h.location==="bottom"?"bottom":"top")}},howl:{buildContainer:function(){return n.bubble.build("howl")},getElements:function(a){return n.bubble.getElements(a)},load:function(a,
b){return n.bubble.load("howl",a,b)},build:function(d){var c=n.bubble.buildContainer("howl");c.data("sf-tipper",b.data("sf-tipper")).data("OnResize",r).data("OnClose",s);a.outside=c;n.bubble.load("howl",c,d);return{container:c,el:d}},positionIt:function(a){return n.bubble.positionIt(a,"howl",h.location==="top"?"top":"bottom")}},bubble:{buildContainer:function(a){var b=f("body > .sf-"+a+":first",o.document);b.length==0&&(b=f('<div class="sf-'+a+'"'+(h.zIndex?' style="position: absolute; z-index: '+
h.zIndex+'"':"")+' data-style="'+a+'"><span class="sf-'+a+'-content"></span><span class="sf-'+a+'-arrow-wrap"><span class="sf-'+a+'-arrow"></span></span></div>'),f("body:first",o.document).append(b),a=="howl"&&(a=f("<div class='sf-tipper-close sf-icn-close2 sf-icn' />"),h.disableClose==!1&&b.append(a)));return b},getElements:function(b){return{container:a.outside,el:b}},load:function(b,d,c){d.css({width:"auto",top:0,left:0});var e=c.attr("data-content")?c.attr("data-content"):h.content,g=parseInt(h.width),
j=!(isNaN(g)||g<=0),g=j?g:a.defaultWidths[b],k=f("<div>"+e+"</div>").css({"max-width":g,position:"absolute",padding:"0",margin:"0","font-family":"arial, verdana, helvetica, sans-serif","font-size":"11px"}).appendTo(document.body),l=k.width(),l=l>g?g:l;k.remove();d.find(".sf-"+b+"-content").html(e);b==="howl"&&(c=c.attr("data-title")?c.attr("data-title"):h.title===""?null:h.title,e=d.find(".sf-"+b+"-heading"),c?e.length<=0?f('<div class="sf-'+b+'-heading">'+c+"</div>").insertBefore(d.find(".sf-"+b+
"-content")):e.text(c):e.length>0&&e.remove());b=d.width();$sf.util.ua.ie&&$sf.util.ua.major<=6&&"maxWidth"in o.document.body.style?d.css({width:b}):d.css(b>g?{width:g,"max-width":g}:b<l&&j?{width:l,"max-width":l}:{width:b})},positionIt:function(a,b,d){function c(b){return{left:b.left,top:b.top,right:b.left+a.container.outerWidth(),bottom:b.top+a.container.outerHeight()}}var d=d!=="bottom"?"top":"bottom",f=d=="top"?"bottom":"top",e=d,k=typeof h.target!=="undefined"?h.target:a.el,l=(k.outerWidth()-
a.container.outerWidth())/2,m=k.offset();if(o!==u){var p=g().offset();m.left+=p.left;m.top+=p.top}var n={top:m.top-a.container.outerHeight()-5,bottom:m.top+k.outerHeight()},l={left:m.left+l,top:n[d]};a.container.css(l);p=function(a,b){var d=j(),f=c(b);return f.left<d.left?Math.abs(f.left-d.left):f.right>d.right?d.right-f.right:0}(k,l,m);k=function(h,g){var k=j(),l=c(g),m=d=="bottom"?-1:1;if(k=l[d]*m<k[d]*m)a.container[m==1?"addClass":"removeClass"]("sf-"+b+"-below");e=k?f:d;return k?n[f]:g.top}(k,
l,m);e=="bottom"?a.container.addClass("sf-"+b+"-below"):a.container.removeClass("sf-"+b+"-below");a.container.css({left:l.left+p+"px",top:k});(function(d){var c=a.container.find(".sf-"+b+"-arrow-wrap");c.css({left:a.container.width()/2-d+c.width()/2+"px"})})(p,l)}}},x={initTrigger:function(b){b.hasClass("sf-tipper-target")||b.addClass("sf-tipper-target").data("sf-tipper-style",h.style);h.groupId&&b.data("sf-tipper-group",h.groupId);(b.is("a")&&b.attr("href")=="#"||b.is("label")||b.parents("label").length>
0)&&b.bind("click.sfTipper",function(){return!1});var d=h.initOnly;if(d==!0)h.initOnly=!1;if(!b.data("sf-tipper")&&(b.data("sf-tipper",parseInt(Math.random()*1E6)),h.style=="tooltip"||h.style=="howl"||h.style=="tourpoint"))if(h.attachIcon==!0&&(b.bind("click.sfTipper dblclick.sfTipper",function(){if(f(":sf-tipper(target="+b.data("sf-tipper")+",open)").length<=0)if(b.data("inClick"))return!1;else b.data("inClick",!0),b.sfTipper(h),setTimeout(function(){b.removeData("inClick")},1E3);else return!1}),
h.style=="tooltip"&&b.addClass("sf-tip-ico")),!h.autoOpen)return!1;a.init=!0;return d==!0?!1:!0},execOpen:function(){return f.isFunction(h.onOpen)==!0&&h.onOpen(b)===!1?!1:!0},requestToReposition:function(){var b=h.reposition;delete a.settings.reposition;if(b==!0&&a.init)return onResize(),!1},requestToClose:function(d){var c=h.close;delete a.settings.close;var e=q(),e=f(".sf-"+e+":first",o.document);if(e.length>0){if(e.data("sf-tipper")==b.data("sf-tipper")){if(c==!0)return outsideMaster=e,x.fadeTipper(!1,
e,!0),!1;a.title&&a.title.html(h.title);a.content&&p(h.content,a.content);n[d].positionIt(n[d].getElements(e));return!1}if(c==!0)return!1;u.setTimeout(function(){b.sfTipper(h)},100);return!1}else if(c==!0)return!1;return!0},requestToCloseTippers:function(b){var d=h.closeTippers;typeof d!=="undefined"&&(d=f.extend({excludeMe:!1},d));delete a.settings.closeTippers;if(typeof d!=="undefined"){var c=d.excludeMe===!0,e=":sf-tipper("+(d.style&&d.style!=="not mine"?"style="+(d.style==="mine"?b:d.style)+",":
"")+"target,open)",g;for(g in f.fn.sfTipper.instances)if(f.fn.sfTipper.instances.hasOwnProperty(g)){var k=f.fn.sfTipper.instances[g],j=k.me.attr("data-style")==="qt"?e.replace(",open",""):e;k.me.is(j)&&(d.style==="not mine"&&k.me.is(":sf-tipper(target,style="+b+")")||(!c||!k.me.is(a.me))&&k.me.sfTipper({close:!0}))}return!1}return!0},requestToSuppressResumeDestroyQuickTips:function(){var b=typeof h.suppressTippers!=="undefined"?"suppress":typeof h.resumeTippers!=="undefined"?"resume":typeof h.destroyTippers!==
"undefined"?"destroy":null;if(b===null)return!0;var d=f.extend({excludeMe:!1},h[b+"Tippers"]);delete a.settings[b+"Tippers"];if(typeof d!=="undefined"){var c=d.excludeMe===!0,e;for(e in f.fn.sfTipper.instances)f.fn.sfTipper.instances.hasOwnProperty(e)&&f.fn.sfTipper.instances[e].me.each(function(){var d=f(this);if(d.is(":sf-tipper(style=qt,target)")&&(!c||!d.is(a.me))){var e={};e[b]=!0;d.sfTipper(e)}});return!1}return!0},fadeTipper:function(d,c,e){if(!a.fading){a.fading=!0;c=c?c:a.outside;f("body",
u.document).die("click",c.data("OnClose"));f("body",o.document).die("click",c.data("OnClose"));b.parentsUntil("body").unbind("scroll",c.data("OnScroll"));f(o).unbind("scroll",c.data("OnResize"));f(o).unbind("resize",c.data("OnResize"));u!=o&&(f(u).unbind("resize",c.data("OnResize")),f(u).unbind("scroll",c.data("OnResize")));var g=function(){a.fading=!1;c.remove()};d===!0||h.disableFade===!0?g():h.fadeToAnchor&&!e?c.animate({top:h.fadeToAnchor.offset().top,left:h.fadeToAnchor.offset().left,opacity:0},
{duration:500,queue:!1,complete:g}):c.fadeOut(300,g)}},display:function(){return f.isFunction(h.onDisplay)===!0&&h.onDisplay(b,n[h.style].getElements(b).container)===!1?!1:!0}};switch(h.style){case "qt":if(!x.requestToCloseTippers(h.style))return b;if(!x.requestToSuppressResumeDestroyQuickTips(h.style))return b;var F=h.resume;if(h.resume)h.suppress=!1,h.resume=!1;var D=n.bubble.buildContainer("qt");f.each(b,function(){var a=f(this);x.initTrigger(a);F===!0&&a.removeAttr("data-suppressed");h.close||
h.suppress||h.destroy?((h.suppress||h.destroy)&&a.unbind("mouseover.sfTipper mouseout.sfTipper"),h.suppress&&a.attr("data-suppressed",!0),h.destroy?(f(":sf-tipper(target,style=qt)").length===1?D.remove():D.hide(),a.removeClass("sf-tipper-target").removeData("sf-tipper"),delete f.fn.sfTipper.instances[k]):D.hide()):a.bind("mouseover.sfTipper",function(){h.suppress||(n.qt.load(D,a),n.qt.positionIt({el:a,container:D}),D.show())}).bind("mouseout.sfTipper",function(){D.hide()})});break;default:(d=x.requestToCloseTippers(h.style))&&
(d=x.requestToSuppressResumeDestroyQuickTips(h.style));if(!d)return b;if(a.init||h.autoOpen)if(d=x.requestToClose(h.style),!d)return b;d=x.initTrigger(b);if(!d)return b;d=x.execOpen();if(!d)return b;d=n[h.style].build(b);n[h.style].positionIt(d);f(o).bind("resize",r);f(o).bind("scroll",r);b.parentsUntil("body").bind("scroll",A);u!=o&&(f(u).bind("resize",r),f(u).bind("scroll",r));x.display();h.disableClose===!1&&u.setTimeout(function(){f("body",u.document).live("click",s);f("body",o.document).live("click",
s)},100);h.resize===!0||h.disableClose===!0?(delete h.resize,d.container.show()):d.container.hide().fadeIn(300)}}};return g.fn(g,e,j)};f.fn.sfTipper.instances={};f.extend(f.expr[":"],{"sf-tipper":function(d,c,g){d=f(d);c=g[3];if(!c||c=="")return d.is(".sf-tipper, .sf-howl, .sf-tourpoint, .sf-qt");var g=c.split(","),b=!1,k=!1,a=f.grep(g,function(a){return a!="target"});a.length<g.length?(g=a,b=d.is(".sf-tipper-target"),k=!0):b=d.is(".sf-tipper, .sf-howl, .sf-tourpoint, .sf-qt");if(b){b=g.length==0;
for(c=0;c<g.length;c++){a=g[c];if(k)switch(a){case "open":b=f(":sf-tipper(target="+d.data("sf-tipper")+"):visible").length>0;break;case "closed":b=f(":sf-tipper(target="+d.data("sf-tipper")+"):visible").length==0;break;default:if(m=a.split("="),m.length>1)switch(m[0]){case "style":b=d.data("sf-tipper-style");b=b===m[1];break;case "group":b=d.data("sf-tipper-group"),b=b===m[1]}else b=!1}else switch(a){case "open":b=d.is(":visible");break;case "closed":b=!d.is(":visible");break;default:var m=a.split("=");
if(m.length>1){if((a=m[1])&&a.length>0)switch(m[0]){case "style":b=d.attr("data-style");b=b===a;break;case "group":b=d.attr("data-group");b=b===a;break;case "target":m=(m=d.data("sf-tipper"))?m.toString():"nope",b=m.toString()===a}}else b=!1}if(b==!1)break}}return b}});return f.fn.sfTipper}($sf.getjQuery())});
define("starfield/sf.base.dialog",["jq!starfield/jquery.mod"],function(){$sf.base.dialog=function(){};$sf.base.dialog.prototype.supr=$sf.base.dialog.prototype;$sf.base.dialog.prototype.execSuper=function(c){var f=[];if(arguments.length>1)for(var d=1;d<arguments.length;d++)f.push(arguments[d]);return this.supr[c].apply(this,f)};$sf.base.dialog.prototype.init=function(c){this.me=c.element;this.context=c.context;this.body=$("body:first",this.context.document);this.dialog=c.dialog;this.content=c.content;
this.inner=c.inner;this.zIndex=c.zIndex;this.fixedPosition=c.fixedPosition===!0;this.fixedHeight=c.fixedHeight===!0;this.fixedWidth=c.fixedWidth===!0;var f=this.me.attr("id")?this.me.attr("id"):"dialog";this.util=new $sf.util.util({logId:f});this.onWindowChange=$.isFunction(c.onWindowChange)?c.onWindowChange:function(){return!0};this.initDimensions()};$sf.base.dialog.prototype.initDimensions=function(){var c=this;c.widthIsExplicit=!1;c.heightIsExplicit=!1;var f=c.me.attr("style"),f=typeof f!=="string"?
[]:f.toLowerCase().split(";");$(f).each(function(d,f){var j=f.split(":");if(j.length>1&&$.trim(j[0])==="width"&&$.trim(j[1]).toLowerCase()!="auto")c.widthIsExplicit=!0;if(j.length>1&&$.trim(j[0])==="height"&&$.trim(j[1]).toLowerCase()!="auto")c.heightIsExplicit=!0});f=c.me.attr("width");if(typeof f==="string"&&f.length>1)c.widthIsExplicit=!0;f=c.me.attr("height");if(typeof f==="string"&&f.length>1)c.heightIsExplicit=!0};$sf.base.dialog.prototype.getViewPort=function(){var c=$(this.context.window),
c={top:0,left:0,width:c.width(),height:c.height()};$sf.util.ua.ie6&&(c.width-=4);if(typeof this.context.window.pageYOffset==="number")c.top=this.context.window.pageYOffset,c.left=this.context.window.pageXOffset;else if(this.context.document.body&&this.context.document.body.scrollTop)c.top=this.context.document.body.scrollTop,c.left=this.context.document.body.scrollLeft;else if(this.context.document.documentElement&&this.context.document.documentElement.scrollTop)c.top=this.context.document.documentElement.scrollTop,
c.left=this.context.document.documentElement.scrollLeft;c.bottom=c.top+c.height;c.right=c.left+c.width;return c};$sf.base.dialog.prototype.getDeltas=function(c,f,d,e,j){c={x:0,y:0,padX:0,padY:0,marginX:e.x,marginY:e.y,idealWidth:c,widthMin:f,heightMin:d};c.padX=this.dialog.outerWidth(!0)-this.dialog.width();c.x=this.dialog.outerWidth(!0)-this.dialog.width()+(this.content.outerWidth(!0)-this.content.width())-c.padX;c.padY=this.dialog.outerHeight(!0)-this.dialog.height();c.y=this.dialog.outerHeight(!0)-
this.dialog.height()+(this.content.outerHeight(!0)-this.content.height())-c.padY;c.extraHeight=$.isFunction(j)?j():0;return c};$sf.base.dialog.prototype.setZIndex=function(c){var f=!isNaN(this.zIndex)?this.zIndex:this.util.zIndex.max()+10;if(typeof this.zIndex==="undefined"||this.zIndex<f)this.zIndex=f;this.dialog.css({"z-index":this.zIndex});$.isFunction(c)&&c(this.zIndex);return this.zIndex};$sf.base.dialog.prototype.sizer=function(c){var f=c.widthAdjustment,d=this,e=d.getDeltas(c.idealWidth,c.widthMin,
c.heightMin,c.margin,c.extraHeight),j=d.getViewPort();return{get:function(){var c=d.dialog.is(":visible");c||d.dialog.show();var b={width:0,height:0};if(d.widthIsExplicit===!1)if(d.me.is("iframe")==!0)b.width=j.width;else{if(b.width=e.idealWidth-e.x,$.isFunction(f))b.width=f(b.width)}else b.width=d.me.outerWidth()+1;b.width+=e.x;var k=j.width-e.marginX*2;if(!d.fixedWidth&&b.width>k)if(k>=e.idealWidth)b.width=k;else if(j.width>e.idealWidth&&b.width>e.idealWidth)b.width=e.idealWidth;if(d.widthIsExplicit===
!0&&b.width<e.idealWidth&&b.width+e.x>=e.idealWidth)b.width=e.idealWidth;if(b.width>j.width)b.width=j.width;if(e.widthMin&&b.width<e.widthMin+e.x)b.width=e.widthMin+e.x;b.innerWidth=b.width-e.x;b.outerWidth=b.width+e.padX;d.inner.css({width:$sf.util.ua.ie6?b.innerWidth+"px":""});d.dialog.width(b.width);b.height=d.me.height()+1;if(d.me.is("iframe")==!1)b.height=d.me.outerHeight()+1;b.height+=e.extraHeight+e.y;b.outerHeight=b.height+e.padY;if(!d.fixedHeight&&b.outerHeight+e.marginY*2>j.height)b.height=
j.height-e.padY-e.marginY*2,b.outerHeight=b.height+e.padY;if(b.height<e.heightMin)b.height=e.heightMin;b.innerHeight=b.height-e.y-e.extraHeight;c||d.dialog.hide();return d.dimensions=b},deltas:e,viewPort:j}};$sf.base.dialog.prototype.positioner=function(c){var f=this;return{get:function(d){var e=f.sizer(c),j=e.get(),g=e.viewPort,d=$.extend({left:parseInt(g.width/2-j.width/2),top:parseInt(g.height/2-j.height/2)},d);return{dimensions:j,position:d,page:g,deltas:e.deltas}}}};$sf.base.dialog.prototype.open=
function(){$(this.context.window).bind("resize scroll",this.onWindowChange)};$sf.base.dialog.prototype.close=function(){$(this.context.window).unbind("resize scroll",this.onWindowChange)};$sf.base.dialog.prototype.destroy=function(){this.close(!0)}});
define("starfield/sf.base.modal",["jq!starfield/jquery.mod","starfield/sf.base.dialog"],function(){$sf.base.modal=function(){};$sf.base.modal.prototype=new $sf.base.dialog;$sf.base.modal.prototype.constructor=$sf.base.modal;$sf.base.modal.constructor=$sf.base.dialog;$sf.base.modal.prototype.init=function(c){var f=this;this.positionTimer=this.position=null;c.onWindowChange=function(){if(f.position&&f.position.canReposition()){var d={disableAnimations:!0};$.isFunction(c.beforeResponseToWindowResize)&&
(d=$.extend(!0,d,c.beforeResponseToWindowResize()));f.position.reposition(d)}};c.fixedPosition=typeof c.fixedPosition!=="boolean"?!$sf.util.ua.ie6:c.fixedPosition;this.execSuper("init",c);this.overlay=$.isPlainObject(c.overlay)?this.overlayer(c.overlay.skin,c.overlay.useAlt,c.overlay.clickToClose):null};$sf.base.modal.prototype.positioner=function(c){function f(b,c){c||(j=b);e.positionTimer=null;if($.isFunction(b.onBeforePosition))b.onBeforePosition();var a=$.extend(!0,{disableAnimations:!1,duration:300,
usePositioning:!0},b);e.inner.stop(!0,!0);e.dialog.stop(!0,!0);e.setZIndex(a.onAfterZIndex);var f=d(a.location);f.disableAnimations=a.disableAnimations;f.positionIsExplicit=$.isPlainObject(a.location)&&a.location.hasOwnProperty("top")&&a.location.hasOwnProperty("left");if($sf.util.ua.ie6)f.disableAnimations=!0,f.position.top+=f.page.top;$.isFunction(a.specialSizing)&&(f=a.specialSizing(f));if(typeof f.disableAnimations!="undefined"&&f.disableAnimations===!0)e.inner.stop().css({height:f.dimensions.innerHeight+
20+"px"}),a.duration=0;e.inner.stop().css("overflow","hidden").animate({height:f.dimensions.innerHeight+"px"},a.duration);e.dialog.css("position",e.fixedPosition?"fixed":"absolute");var g={width:f.dimensions.width+"px",height:f.dimensions.height+"px"};if(a.usePositioning===!0||f.positionIsExplicit===!0)g.left=f.position.left+"px",g.top=f.position.top+"px";e.dialog.stop().css("overflow","").animate(g,a.duration,function(){var b=a.usePositioning,d=a.afterPositioning,c=a.onAfterPosition,f=e.inner.outerWidth(),
g=e.inner.outerHeight(),k=e.me.outerWidth(),l=e.me.outerHeight()+e.me.position().top,h=e.dialog.position(),j=e.inner[0].scrollHeight;if(!(k<=f&&l<=g)){e.inner.css("overflow","");j>g&&!e.fixedHeight&&(e.inner.css("width",f+20+"px"),b&&e.dialog.css({left:h.left-10+"px"}),k=e.dialog.width(),e.dialog.css({width:k+20+"px"}));l=e.inner[0].scrollWidth;k={};if($.isFunction(d))k=d();else if(l>f&&!e.fixedWidth){e.inner.css("height",g+20+"px");d=e.dialog.height()+20;f=$(e.context.window).height();h=e.fixedPosition?
(f-d)/2:h.top-10;if(b)k.top=h+"px";k.height=d+"px"}(k.top||!b&&k.height)&&e.dialog.css(k);$.isFunction(c)&&c()}});e.positionInfo=f}function d(b){return g.get(b)}var e=this,j=null,g=e.execSuper("positioner",c);e.position={set:f,get:d,reposition:function(b){e.initDimensions();var d=$.extend({async:!1,disableAnimations:!0,usePositioning:!0,callback:null},b),a=$.extend({},j,{disableAnimations:d.disableAnimations,usePositioning:d.usePositioning,location:$.isPlainObject(d.location)?d.location:j.location,
onAfterPosition:function(){$.isFunction(d.callback)&&d.callback();if($.isFunction(j.onAfterPosition))j.onAfterPosition()}});if(d.async==!0){if(e.positionTimer==null)e.positionTimer=setTimeout(function(){f(a,!0)},50)}else f(a,!0)},canReposition:function(){return j!==null}};return e.position};$sf.base.modal.prototype.overlayer=function(c,f,d){function e(){if($sf.util.ua.ie6||c==="fos"){var a=j.getViewPort();g.css({top:a.top+"px",left:a.left+"px",width:a.width+"px",height:a.height+"px"})}}var j=this,
g=null,b="sf-dialog-overlay-"+Math.round(Math.random()*65535),c=typeof c==="fos"?"fos":"app",k=c==="fos"?"sf-g-modal-overlay":"sf-dialog-overlay",f=f===!0,a=j.body,m=j.body.find("embed[flashvars]").length>0&&$sf.util.ua.ff,l={};return{show:function(){if(!m){var w=$sf.util.ua.ie7||$sf.util.ua.ie6?a.parent("html"):a;l.overflow=w.css("overflow");l["overflow-x"]=w.css("overflow-x");l["overflow-y"]=w.css("overflow-y");w.css({overflow:"hidden","overflow-x":"hidden","overflow-y":"hidden"});a.parent("html").css({height:"100%"})}g=
$("#"+b+"-overlay");g.length===0&&(g=$("<div />").attr("id",b+"-overlay").addClass(k).prependTo(a));c!=="fos"&&f&&g.addClass("sf-dialog-overlay-alt");g.css({display:"block","z-index":j.zIndex-1,position:$sf.util.ua.ie6||c==="fos"?"absolute":"fixed"});e();$.isFunction(d)&&g.bind("click",d);g.fadeIn(500,function(){g.css({display:"block"})})},hide:function(b){if(g){g.fadeOut(!b?500:0,function(){g.remove()});if(!m){a.parent("html").css({height:""});for(var c in l)l.hasOwnProperty(c)&&(b=$sf.util.ua.ie7||
$sf.util.ua.ie6?a.parent("html"):a,l[c]!=null&&l[c]!=void 0?b.css(c,l[c]):b.css(c,"visible"))}$.isFunction(d)&&g.unbind("click")}},size:e}};$sf.base.modal.prototype.open=function(c){$.isPlainObject(c)&&this.position&&this.position.canReposition()&&this.position.reposition(c);this.overlay&&this.overlay.show();this.execSuper("open")};$sf.base.modal.prototype.close=function(c){this.overlay&&this.overlay.hide(c);this.execSuper("close",c)}});
define("starfield/sf.base.flyout",["jq!starfield/jquery.mod","starfield/sf.base.dialog"],function(){$sf.base.flyout=function(){};$sf.base.flyout.prototype=new $sf.base.dialog;$sf.base.flyout.prototype.constructor=$sf.base.flyout;$sf.base.flyout.constructor=$sf.base.dialog;$sf.base.flyout.prototype.init=function(c){var f=this;this.positionTimer=this.position=null;c.onWindowChange=function(){if(f.position&&f.position.canReposition()){var d={disableAnimations:!0};$.isFunction(c.beforeResponseToWindowResize)&&
(d=$.extend(!0,d,c.beforeResponseToWindowResize()));f.position.reposition(d)}};this.execSuper("init",c);this.dialogZIndex=c.zIndex;this.anchor=this.anchorer(c.anchor)};$sf.base.flyout.prototype.anchorer=function(c){var c={origin:c},f=this.dialog.attr("id");c.origin.addClass("sf-flyout-origin").attr("data-flyout",f);this.anchor=c;this.setZIndex({dialogZIndex:this.dialogZIndex,resetAnchor:!0});return c};$sf.base.flyout.prototype.setZIndex=function(c){var c=c?c:{},f=c.dialogZIndex&&typeof c.dialogZIndex===
"number"&&c.dialogZIndex>0?c.dialogZIndex:this.util.zIndex.max()+10;this.dialogZIndex=f;this.dialog.css({"z-index":f});$.isFunction(c.callback)&&c.callback(f);if(c.resetAnchor===!0){c=this.anchor.origin;c.css("position")=="static"&&c.css("position","relative");this.zIndex=this.util.zIndex.get(c);this.anchor.originalZIndex=this.zIndex;if(this.zIndex==0)this.zIndex=3;c.css("zIndex",this.zIndex)}};$sf.base.flyout.prototype.positioner=function(c){function f(b,c){c||(j=b);if($.isFunction(b.onBeforePosition))b.onBeforePosition();
var a=g.get(),f=e.dialog,l=e.anchor.origin,w={t:0,l:0},z=$.extend({width:0,height:0},b.containerOffset);e.setZIndex({dialogZIndex:e.dialogZIndex,callback:b.onAfterZIndex});if(f.get(0).ownerDocument!==l.get(0).ownerDocument&&($("iframe").each(function(){$(this).contents().find(l).length>0&&(iframe=$(this))}),iframe&&iframe.length>0))w.l=iframe.offset().left,w.t=iframe.offset().top;f=d(b.anchorAttachment,l,f,a.page,w,{width:function(){return z.width},height:function(){return z.height}});w=f.y+f.x;e.dialog.css({top:f.coords.top+
"px",left:f.coords.left+"px"}).attr("data-idealAttachment",b.anchorAttachment).attr("data-actualAttachment",w);if($.isFunction(b.onAfterPosition))b.onAfterPosition();e.positionInfo=a}function d(b,d,a,c,f,e){function g(a,b,d,c){var f=a.replace("m","").replace("c",""),e=n.direction(f),c=c===1?1:-1,k="tb".indexOf(f)>-1?"height":"width",b=s[k]+d[k](b)*c,b=a.length>1?Math.floor(b/2):b,a="lr".indexOf(f)>-1?p.l:p.t;return Math.floor(h[f]+a+b*e)}function j(a,b){return g(a,b,h,-1)}function r(a,b){return g(a,
b,u,1)}function A(a){for(var b=[[0,0],[1,0],[2,h.width<=s.width?0:1],[3,h.width<=s.width?0:1],[2,h.width<=s.width?1:0],[3,h.width<=s.width?1:0],[0,1],[1,1]],d=!1,a=a!==1?0:a,c=a===0,f=0;f<b.length;f++){var d=b[f][0],e=b[f][1],g=c,d=d>0?t.v==="m"?t.grid[d][0]:t.opp(d):t.v,e=e>0?o.opp(e):o.v,k;k=d;var l=e,m=!1,g=typeof g==="undefined"?!0:g,m="ut".indexOf(k)>-1?t.opp(1,"t"):"fb".indexOf(k)>-1?t.opp(1,"b"):"m",l=l==="c"?l:o.opp(1,l),w=m+l;if(k=m="ufc".indexOf(k)>-1?x(m,w,r)&&x(l,w,j,g):x(l,w,r)&&x(m,
w,j,g))t.v=d,o.v=e;if(d=k)break}!d&&a===0&&A(1);return d}var b=b.substr(0,1)==="l"?"f"+b.substr(1):b,p={t:c.top,b:c.bottom,l:c.left,r:c.right},s={el:a,width:a.outerWidth(!0),height:a.outerHeight(!0)},h=d.offset();h.t=Math.floor(d.offset().top-(p.t-f.t));h.l=Math.floor(d.offset().left-(p.l-f.l));h.width=function(){return Math.floor(d.outerWidth())};h.height=function(){return Math.floor(d.outerHeight())};h.r=h.l+h.width();h.b=h.t+h.height();h.m=h.t+Math.floor(h.height()/2);h.mt=h.m-Math.floor(s.height/
2);h.mb=h.m+Math.floor(s.height/2);h.c=h.l+Math.floor(h.width()/2);h.cl=h.c-Math.floor(s.width/2);h.cr=h.c+Math.floor(s.width/2);var u=e,o={v:b.substr(1,1),grid:[["l","r","c"],["r","l","c"]],opp:function(a,b){var b=b?b:o.v,d=$.inArray(b,o.grid[0]);return o.grid[a][d]}},t={v:b.substr(0,1),grid:[["t","b","f","u","m"],["b","t","u","f","m"],["u","f","b","t","m"],["f","u","t","b","m"]],opp:function(a,b){var b=b?b:t.v,d=$.inArray(b,t.grid[0]);return t.grid[a][d]}},n={get:function(a){return"tbm".indexOf(a)>
-1?t:o},opposite:function(a){return"tbm".indexOf(a)>-1?o:t},direction:function(a){return"tl".indexOf(a)>-1?-1:1},centerLimits:function(a){return"mc".indexOf(a)<0?null:a==="m"?["t","b"]:["l","r"]}},x=function(a,b,d,c){var f=!1,e=n.centerLimits(a);if(e!==null)f=x(a+e[0],b,d,c)&&x(a+e[1],b,d,c);else{var f=a.replace("m","").replace("c",""),e=n.get(f).opp(1,f),g=n.direction(f),k=d(a,b)*g,a=a.length>1?d(e,b)*g:h[e]*e;(f=p[f]*g>=k)&&c===!0&&(f=f&&p[e]*g<=a)}return f};A();b={top:t.v==="t"?h.t:t.v==="b"?h.b-
s.height:t.v==="u"?h.b+u.height():t.v==="f"?h.t-s.height-u.height():h.mt,left:o.v==="r"?h.l:h.r};b.left="tbm".indexOf(t.v)>-1?o.v==="r"?h.l-(s.width+u.width()):o.v==="l"?h.r+u.width():h["m"+v.v]:o.v==="r"?h.r-s.width:o.v==="l"?h.l:h.cl;b.left+=p.l;b.top+=p.t;return{coords:b,y:t.v==="f"?"l":t.v,x:o.v}}var e=this,j=null,g=e.execSuper("positioner",c);e.position={set:f,get:d,reposition:function(b){e.initDimensions();var d=$.extend({},j,{anchorAttachment:b.anchorAttachment,onAfterPosition:function(){$.isFunction(b.callback)&&
b.callback();if($.isFunction(j.onAfterPosition))j.onAfterPosition()}});f(d,!0)},canReposition:function(){return j!==null}};return e.position};$sf.base.flyout.prototype.open=function(c){$.isPlainObject(c)&&this.position&&this.position.canReposition()&&this.position.reposition(c);this.overlay&&this.overlay.show();this.execSuper("open")};$sf.base.flyout.prototype.close=function(c){this.execSuper("close",c)}});var $sfDialog=null;
define("starfield/sf.dialog","i18n!starfield/sf.i18n/duel,starfield/sf.base.modal,starfield/sf.base.flyout,foscss!starfield/sf.core.css,jq!starfield/jquery.mod,starfield/sf.tabs,starfield/sf.util".split(","),function(c){var f=c.common;return function(d){d.fn.sfDialog=function(e,j){var g=d(this),b=g.attr("id");if(b==null||b.length==0)b="sfDialog"+Math.round(Math.random()*65535),g.attr("id",b);var k=d.fn.sfDialog.instances[b];if(k!=null)return k.me_this=this,k.me=g,k.fn(k,e,j);k=d.fn.sfDialog.instances[b]=
{me_this:this,me:d(this),initialized:!1,isEnabled:!0,fn:function(a,b,e){function k(b,e){a.meId=a.me.attr("id");if(e!==!0&&typeof b!=="undefined"&&typeof b.restore!=="undefined")R(b);else{if(typeof a.settings=="undefined")a.settings=d.extend(!0,{autoCloseOnCancel:!0,autoOpen:!0,autoResize:!1,buttons:void 0,buttonAlign:"center",cancelDisabled:!1,closeOnEscape:!0,context:self,destroyOnClose:null,dialogWidthIdeal:500,veilWidthIdeal:450,dialogHeightMin:200,disabled:!1,draggable:!0,load:null,loadFresh:!0,
modal:!0,mode:"classic",message:null,noConflict:!1,overlayAlt:!1,page:null,preload:null,restore:!1,save:!1,title:c["sf.dialog"].title,titleHidden:!1,veil:null,zIndex:2E9,onButtonClick:null,onOpen:null,onClose:null,onCancel:null,onTabSelected:null,onLoad:null,onRestore:null,onWizardFinish:null,onDrag:null,onPositioned:null,footer:"",anchor:void 0,anchorAttachment:"tl",dialogOffset:void 0,texts:c["sf.dialog"]},b),a.msgOverlay=null,a.wizardButtons=!1,a.hideButtons=!1;else{if(a.mode!==a.settings.mode)a.settings.buttons=
void 0;if(typeof b!=="undefined"&&typeof b.buttons!=="undefined")a.settings.buttons=[];a.settings=d.extend(!0,a.settings,b)}a.meIsFrame=a.me.is("iframe")===!0;if(typeof a.mode!=="undefined"&&a.mode!==a.settings.mode)a.wizardButtons=a.settings.mode==="wizard",a.settings.buttons=typeof b!=="undefined"&&typeof b.buttons!=="undefined"?b.buttons:void 0,a.settings.buttonAlign=typeof b!=="undefined"&&typeof b.buttonAlign!=="undefined"?b.buttonAlign:"center";typeof a.settings.buttons==="undefined"?(a.wizardButtons=
a.settings.mode==="wizard",a.settings.buttons=[{id:"ok",text:f.ok},{id:"cancel",text:f.cancel,cancel:!0}]):a.settings.hideButtons=a.settings.buttons.constructor==Array&&a.settings.buttons.length===0;a.mode=a.settings.mode;a.buttonDefaults={app:{enabledClasses:"sf-btn-primary",disabledClasses:"sf-btn-primary sf-btn-dsabld"},fos:{enabledClasses:"sf-g-btn-lg sf-g-btn-prg",disabledClasses:"sf-g-btn-lg sf-g-btn-prg-inactive"}};a.context=a.settings.context;a.usePositioning=!0;a.positionOverridden=!1;a.settings.noConflict==
!1&&($sfDialog=g);if(a.me.parent().is(".sf-dialog-inner,.sf-g-modal-content")==!0){if(a.settings.veil)a.base.fixedPosition=!1;a.inner=a.me.parent();a.content=a.inner.parent();a.buttons=a.content.children(".sf-dialog-buttons,.sf-g-modal-buttonpane");a.dialog=a.content.parent(".sf-dialog,.sf-g-modal");a.title=a.dialog.children(".sf-dialog-title,.sf-g-modal-header");a.close=a.dialog.children(".sf-dialog-close,.sf-g-modal-close")}else{a.originalParent=a.me.parent();a.hasParent=a.originalParent.length>
0;if(a.settings.destroyOnClose===null)a.settings.destroyOnClose=a.hasParent===!1;a.dialog=d("<div/>").addClass($sf.skin=="fos"?"sf-g-modal":"sf-dialog");a.title=d("<h3/>").addClass($sf.skin=="fos"?"sf-g-modal-header":"sf-dialog-title");a.close=d("<span/>").addClass($sf.skin=="fos"?"sf-g-modal-close":"sf-dialog-close sf-icn-close1 sf-icn");a.content=d("<div/>").addClass($sf.skin=="fos"?"sf-g-modal-container":"sf-dialog-content");a.inner=d("<div/>").addClass($sf.skin=="fos"?"sf-g-modal-content":"sf-dialog-inner");
a.buttons=d("<div/>").addClass($sf.skin=="fos"?"sf-g-modal-buttonpane":"sf-dialog-buttons");a.footer=null;a.tabs=null;a.tabLastSelected=null;a.tabsHeight=0;a.content.append(a.inner);a.content.append(a.buttons);a.dialog.append(a.close);a.dialog.append(a.title);a.dialog.append(a.content);a.meBody=d("body:first",a.context.document);a.meBody.append(a.dialog);a.preventOverflowChanges=a.meBody.find("embed[flashvars]").length>0&&$sf.util.ua.ff;a.innerOverflow="";q()}if(a.settings.veil)a.base.overlay&&a.base.overlay.hide(!0),
a.settings.titleHidden=!0,a.settings.veil.sfDialog("setOnDrag",ba);a.settings.titleHidden==!0?a.title.hide():a.title.show();a.settings.cancelDisabled==!0||a.settings.veil?a.close.hide():a.close.show();a.settings.veil?a.dialog.addClass("sf-dialog-veil sf-g-modal-veil"):a.settings.modal==!0?a.dialog.addClass("sf-dialog-modal"):a.dialog.addClass("sf-dialog-modeless");if(a.initialized==!1)a.draggable=!1,a.isOpen=!1,a.overlay=null;r();n();p();if(a.settings.footer!=null&&a.settings.footer!=="")a.footer=
d("<div>"+a.settings.footer+"</div>").addClass($sf.skin=="fos"?"sf-g-modal-footer":"sf-dialog-footer"),a.content.append(a.footer);a.me.removeClass("sf-dialog");a.meIsFrame&&a.me.attr({scrolling:"no",frameborder:"0"}).css({overflow:"visible"});d.inArray(a.me[0],a.inner.children())<0&&a.inner.empty().append(a.me);a.me.show();a.initialized=!0;E()==!1&&(d(a.context.window).bind("unload",S),d(a.context.document).bind("keydown",M));e!==!0&&a.settings.autoOpen==!0&&J(a.settings);e!==!0&&a.settings.save!=
null&&T(b);e!==!0&&a.settings.load!=null&&Q(b);if(typeof a.settings.message=="string")a.msgOverlay||P(),require("starfield/sf.msg.overlay",function(){a.msgOverlay=a.dialog.sfMsgOverlay({style:"progress",message:a.settings.message})});else if(a.msgOverlay)O(),a.msgOverlay.sfMsgOverlay({message:null}),a.msgOverlay=null;j()}}function j(){if(a.meIsFrame)try{var b=F(a.me.contents().find("html")[0].ownerDocument);typeof b!=="undefined"&&b.duelDialogInit&&b.duelDialogInit(a.me)}catch(d){}}function q(){typeof a.settings.anchor!==
"undefined"&&!a.settings.veil?(a.base=new $sf.base.flyout,a.base.init({element:a.me,anchor:a.settings.anchor,context:a.context,dialog:a.dialog,content:a.content,inner:a.inner,zIndex:a.settings.zIndex+(!a.settings.veil?a.settings.modal===!0?2:0:4),beforeResponseToWindowResize:function(){return{anchorAttachment:a.settings.anchorAttachment}}})):(a.base=new $sf.base.modal,a.base.init({element:a.me,context:a.context,dialog:a.dialog,content:a.content,inner:a.inner,zIndex:a.settings.zIndex+(!a.settings.veil?
a.settings.modal===!0?2:0:4),overlay:a.settings.modal===!0&&!a.settings.veil?{skin:$sf.skin,useAlt:a.settings.overlayAlt}:null,fixedPosition:!(a.settings.veil||/msie|MSIE 6/.test(navigator.userAgent)||a.positionOverridden),beforeResponseToWindowResize:function(){a.usePositioning=!a.positionOverridden;return{usePositioning:a.usePositioning}}}))}function r(){if(a.settings.draggable==!1&&a.draggable==!0)a.title.draggable("destroy"),a.dialog.unbind("drag.sfd"),a.dialog.draggable("destroy"),a.title.css("cursor",
"default"),a.draggable=!1,a.usePositioning=!a.positionOverridden;else if(a.settings.draggable==!0&&typeof a.me.draggable!="undefined")a.draggable=!0,a.dialog.draggable({handle:a.title}),a.title.css("cursor","move"),U(function(){a.usePositioning=!1},"sfd")}function A(b){typeof a.me.draggable!="undefined"&&a.dialog.draggable("option","disabled",!b);a.title.css("cursor",b?"move":"default")}function p(b){var c=a.settings.texts;d("*",a.buttons).unbind().remove();if(a.settings.hideButtons)a.buttons.hide();
else{a.buttonsIdx={};a.cancel=null;var e=a.settings.buttons;if(a.wizardButtons&&typeof a.tabs_menu!=="undefined"){var h=a.tabs_menu.find("ul:first"),g=e&&e.length>0&&e[1].id=="back",k=h.children("li:first").is(".sf-tabs-wiz-step-current"),h=h.children("li:last").is(".sf-tabs-wiz-step-current");a.settings.buttons=e=[{id:"cancel",text:c.wizardCancel,cancel:!0},{id:"back",text:c.wizardBack,isDisabled:k||g&&e[1].isDisabled},{id:h?"finish":"next",text:h?c.wizardFinish:c.wizardNext,isDisabled:g&&e[2].isDisabled}];
if($sf.skin=="fos")e[1].enabledClasses="sf-g-btn-lg sf-g-btn-sec",e[1].disabledClasses="sf-g-btn-lg sf-g-btn-sec-inactive"}typeof b!="undefined"&&b==!0&&(e=[]);e.length==0&&e.push({id:"cancel",text:f.cancel,cancel:!0});for(b=0;b<e.length;b++)if(g=e[b],g.type==="closebox"&&a.close){if(g.attributes)for(var j in g.attributes)g.attributes.hasOwnProperty(j)&&a.close.attr(j,g.attributes[j])}else{g=d.extend(!0,{id:"",index:b,text:c.button,cancel:!1,style:"button",onClick:null,isDisabled:!1},e[b]);if(g.id.length==
0)g.id="sfButton"+parseInt(Math.random()*65535);if(g.text.length==0)g.text=c.button;if(a.cancel==null&&b==e.length-1&&g.text==f.cancel)g.cancel=!0;if(g.cancel==!0)g.style="link";g.index=b;g.button=null;k=a.isEnabled==!0&&g.isDisabled==!1?"enabledClasses":"disabledClasses";g.style=="link"?(g.button=d('<a href="#" />').text(g.text),g.button.addClass(g[k]?g[k]:$sf.skin!=="fos"?"sf-dialog-link":"")):(g.button=d('<a href="#" />'),g.button.addClass(g[k]?g[k]:a.buttonDefaults[$sf.skin][k]),g.button.text(g.text),
e[b].hasIcon&&g.button.prepend("<span />"));g.button.attr("data-button",g.id);g.button.bind("click",W);if(g.attributes)for(j in g.attributes)g.attributes.hasOwnProperty(j)&&g.button.attr(j,g.attributes[j]);a.buttons.append(g.button);$sf.skin==="fos"&&a.buttons.append("\n");if(g.cancel==!0)a.cancel=g.button;e[b]=g;a.buttonsIdx[g.id]=g}a.isEnabled==!1&&$sf.skin!="fos"&&a.buttons.append('<div style="display: block; position: absolute;" class="sf-dialog-overlay sf-dialog-overlay-alt"></div>');V(a.settings.buttonAlign)}}
function s(b){if(typeof b=="string")b=a.buttonsIdx[b];else{if(b<0||b>=a.settings.buttons.length)return null;b=a.settings.buttons[b]}typeof b=="undefined"&&(b=null);return b}function h(b){if(d.isArray(b)==!0)a.settings.buttons=b,p()}function u(a){a=s(a);return a==null?null:a.isDisabled}function o(a){a=s(a);if(a!=null)a.isDisabled=!1,p()}function t(a){a=s(a);if(a!=null)a.isDisabled=!0,p()}function n(){a.close.unbind();var b=a.me.attr("data-title");a.title.html(b!=null&&b.length>0?b:a.settings.title);
a.close.bind("click",X);x();D()}function x(){if(a.tabs!=null)a.tabs.sfTabs("destroy"),a.tabs=null,a.tabsHeight=0;var b;if(a.meIsFrame)try{b="wizard toggle tabs".indexOf(a.mode)>-1?a.me.contents().find(".sf-dialog-tab,.sf-tabs-content"):d("body > .sf-dialog-tab, body > .sf-tabs-content, body > div > .sf-dialog-tab, body > div > .sf-tabs-content",a.me.contents())}catch(c){return}else b=a.me.children(".sf-dialog-tab,.sf-tabs-content");if(b.length==0)a.title.removeClass("sf-g-modal-header-tabs");else{b.css({padding:0});
var e;for(e=0;e<b.length;e++){var f=b.eq(e);f.is(".sf-dialog-tab")==!0&&f.removeClass("sf-dialog-tab").addClass("sf-tabs-content");f.is(".sf-dialog-tab-selected")==!0&&f.addClass(".sf-tabs-actv-content").removeClass(".sf-dialog-tab-selected");f.is(".sf-dialog-tab-hidden")==!0&&f.addClass(".sf-tabs-hidden").removeClass(".sf-dialog-tab-hidden")}b=b.eq(0).parent();a.tabs=b.sfTabs({mode:a.mode,bborder:!0,tabControlContext:a.meIsFrame?F(a.me.contents().find("html")[0].ownerDocument):window.self,onTabSelected:function(b,
c,e){if(d.isFunction(a.settings.onTabSelected)==!0&&a.settings.onTabSelected(a.me,c,e)==!1)return!1;a.mode=="wizard"&&setTimeout(function(){p();D()},0);c=(b=$sf.util.ua.ie&&$sf.util.ua.major<9)?10:0;a.meIsFrame&&(a.me.width(e.outerWidth()+c),a.me.height(e.outerHeight()+c),b&&(a.me.attr("frameborder","0"),a.me.css({overflow:"hidden",border:"none"})));a.tabsMode=="wizard"&&setTimeout(function(){p();D()},0);C({async:!0,noanim:!1})}});a.tabs_menu=b.children(".sf-tabs:first,.sf-g-tabs:first,.sf-tabs-wiz:first,.sf-tabs-toggle:first");
if(a.tabs_menu.length==0)a.tabs_menu=a.me.parent().children(".sf-tabs:first,.sf-g-tabs:first,.sf-tabs-wiz:first,.sf-tabs-toggle:first");a.content.before(a.tabs_menu);$sf.skin=="fos"&&a.title.addClass("sf-g-modal-header-tabs");if(a.dialog.is(":visible")==!0)a.tabsHeight=a.tabs_menu.outerHeight()}}function F(a){return a.parentWindow||a.defaultView}function D(){if(a.mode=="wizard"&&typeof a.tabs_menu!=="undefined"){var b=a.tabs_menu.find("ul:first"),c=b.children("li.sf-tabs-wiz-step-current").index(),
b=b.children().length,e=a.title.children("span.sf-dialog-wiz-title-steps");e.length==0&&(e=d('<span class="sf-dialog-wiz-title-steps"></span>').appendTo(a.title));e.text("("+a.settings.texts.stepOf.sfFormat(c+1,b)+")")}}function y(b,d){b!=!0&&B(!0);if(a.initialized!=!1){a.initialized=!1;if(a.meIsFrame){var c=function(){try{if(typeof a.tabs!=="undefined"&&a.tabs!=null)a.tabs.sfTabs("destroy"),a.tabs=null,a.tabsHeight=0}catch(b){}};d?c():setTimeout(c,500)}a.oldButtons=a.settings.buttons;if(a.mode!==
"classic")a.settings.buttons=void 0;b&&a.settings.destroyOnClose===!1||(typeof a.dialog!="undefined"&&(c=function(){a.hasParent===!0&&(a.me.hide(),a.originalParent.append(a.me));a.base.destroy();delete a.base;a.dialog.remove();delete a.dialog},d?c():setTimeout(c,1E3)),a.contentShiftEventId&&($sf.util.event.off(a.contentShiftEventId),delete a.contentShiftEventId),delete a.settings)}}function B(b,c,e,f){if(E()!=!1&&(a.resizeTimer&&(clearInterval(a.resizeTimer),delete a.resizeTimer),a.settings.noConflict==
!1&&($sfDialog=g),typeof b=="undefined"&&(b=!1),typeof c=="undefined"&&(c=null),typeof e=="undefined"&&(e=!1),(!((c!=null&&c.cancel==!0||e===!0)&&d.isFunction(a.settings.onCancel)==!0)||!(a.settings.onCancel(c,e)==!1&&b==!1))&&!(d.isFunction(a.settings.onClose)==!0&&a.settings.onClose(c,e)==!1&&b==!1))){d.fn.sfDialog.opens--;d.fn.sfDialog.saves={};d.fn.sfDialog.savesArr=[];a.base.close();a.dialog.unbind();a.buttons&&d("*",a.buttons).unbind();a.tabs&&a.me.find(".sf-tabs-menu *").unbind();a.close&&
d("*",a.close).unbind();d(a.context.window).unbind("unload",S);d(a.context.document).unbind("keydown",M);if(a.draggable==!0)a.dialog.draggable("destroy"),a.title.css("cursor","default"),a.draggable=!1;a.settings.veil?(a.settings.veil.sfDialog("enable").sfDialog({closeOnEscape:a.veilCloseOnEscape,onClose:a.veilClose}),ca()):a.dialog.fadeOut(f?0:500);a.isOpen=!1;y(!0,f)}}function C(b){b=d.extend(!0,{async:!1,noanim:!0,usePositioning:a.usePositioning===!0,anchorAttachment:a.settings.anchorAttachment,
callback:null},b);b.disableAnimations=b.noanim;a.base.position&&a.base.position.reposition(b)}function M(b){if(!a.msgOverlay){switch(b.keyCode){case 27:typeof a.settings!=="undefined"&&a.settings.cancelDisabled==!1&&a.settings.closeOnEscape==!0&&a.isEnabled==!0&&E()==!0&&setTimeout(N,10)}return!0}}function W(b){d(document.body).trigger("click",b);var c=d(b.target).closest("a[data-button]");if(c.length==0)return!1;var e=c.attr("data-button");if(e.length==0)return!1;c=a.buttonsIdx[e];if(c!=null){if(c.cancel==
!1&&(a.isEnabled==!1||c.isDisabled==!0))return!1;if(d.isFunction(c.onClick)==!0&&c.onClick(a.me,e,c,b)==!1)return b.stopPropagation(),!1;if(typeof a.settings!="undefined"){if(d.isFunction(a.settings.onButtonClick)==!0&&a.settings.onButtonClick(a.me,e,c,b)==!1)return b.stopPropagation(),!1;if(c.cancel==!0&&a.settings.autoCloseOnCancel==!0)return B(!1,c,!1),!1;if(a.mode==="wizard")switch(b=L(),e){case "back":b>0&&(G(b-1),p());break;case "next":a.settings.buttons[1].isDisabled=!1;G(b+1);p();break;case "finish":a.settings.buttons[1].isDisabled=
!1,b=!0,d.isFunction(a.settings.onWizardFinish)&&(b=a.settings.onWizardFinish(c,!1)!=!1),b&&B(!1,c,!1)}}}return!1}function J(b){var c=typeof b!=="undefined"&&b.fromMethod===!0;if(a.initialized===!1||c){var e=b;if(c&&typeof a.settings!=="undefined"){e=d.extend(!0,{},a.settings);if(!a.hasParent)a.base.overlay&&a.base.overlay.hide(!0),a.me=a.me.remove();a.settings.destroyOnClose=!0;B(!0,null,null,!0);a.settings=e;delete b.fromMethod}k(b)}a.settings.noConflict===!1&&($sfDialog=g);if(E()!==!0){a.dialog.show();
a.buttonsWidth=0;a.buttons.children().each(function(b,c){var e=d(c).outerWidth(!0);a.buttonsWidth+=e});a.isOpen=!0;a.base.open();H(!0);if(!a.contentShiftEventId)a.contentShiftEventId=$sf.util.event.on("contentShift",C);if(a.settings.veil)b=a.settings.veil.sfDialog("settings"),a.veilClose=b.onClose,a.veilCloseOnEscape=b.closeOnEscape,a.settings.veil.sfDialog("disable").sfDialog({onClose:da,closeOnEscape:!1}),I();if(d.isFunction(a.settings.onOpen)==!0)a.settings.onOpen(a.dialog,a.me);b=L();G(b<0?0:
b);if(a.settings.autoResize)a.resizeTimer=setInterval(C,500);d.fn.sfDialog.opens++}}function X(){B(!1,null,!0)}function E(){return a.initialized&&a.isOpen}function O(){if(!(a.isEnabled==!0||a.initialized==!1)){a.isEnabled=!0;a.inner.find(".sf-dialog-overlay,.sf-dialog-overlay-alt").remove();var b=function(){a.inner.css("overflow",a.innerOverflow)};$sf.util.ua.webkit?setTimeout(b,200):b();p()}}function P(){if(!(a.isEnabled==!1||a.initialized==!1))a.isEnabled=!1,a.innerOverflow=a.inner.css("overflow"),
a.inner.css("overflow","hidden"),a.inner[0].scrollTop=0,$sf.skin!="fos"&&a.inner.append('<div style="display: block; position: absolute;" class="sf-dialog-overlay sf-dialog-overlay-alt"></div>'),p()}function Y(a){E()==!0?B():J(a)}function N(){if(E()==!1)return!0;a.settings.noConflict==!1&&($sfDialog=g);if(a.cancel!=null){if(d.isFunction(a.cancel.onClick)==!0&&a.cancel.onClick(a.me,a.cancel.id)==!1)return!1;if(d.isFunction(a.settings.onButtonClick)==!0&&a.settings.onButtonClick(a.me,a.cancel.id)==
!1)return!1}B(!1,null,!0);return!0}function Z(a){a=d.extend(!0,{preload:[]},a);d.each(a.preload,function(a,b){var c=b.split("#")[0];typeof d.fn.sfDialog.resources[c]=="undefined"&&(c.toLowerCase().lastIndexOf(".js")==c.length-3?(c=c.substr(0,c.length-3),require(c,function(a){a=a.join("\r\n");d.fn.sfDialog.resources[c]={url:c,data:a}})):d.ajax({dataType:"text",url:c,success:function(a){d.fn.sfDialog.resources[c]={url:c,data:a}},error:function(){d.fn.sfDialog.resources[c]={url:c,data:null}}}))})}function K(b,
c){c.split("#");var e="";if(a.settings.page!=null)e=a.settings.page;xml=d(b);if(e.length>0){var f=xml.filter("#"+e),e=xml.filter('[data-page-id="'+e+'"]');a.me.empty().attr({style:f.attr("style"),"data-title":f.attr("data-title")}).append(f.html());e.length>0&&a.meBody.append(e)}else f=xml.find("title"),f.length>0&&a.title.text(f.text()),a.me.empty().append(xml)}function aa(){var b={};if(a.load_url==null)return b;var d=a.load_url.split("#");if(d.length<2)return b;d=d[1].split("&");for(i=0;i<d.length;i++)v=
d[i],args=v.split("="),args.length==2&&(b[args[0]]=args[1]);return b}function Q(b){var c=d.extend(!0,{load:null},b);if(!(typeof c.load!="string"||c.load.length==0)){a.load_url=b.load;b.load=null;typeof a.settings!=="undefined"&&a.settings.loadFresh===!0&&(delete a.settings,k(b,!0));var e=a.load_url.split("#")[0],c=d.fn.sfDialog.resources[e];if(typeof c!="undefined"){var f=!1;c.data!=null?(K(c.data,a.load_url),f=!0):a.me.html(a.settings.texts.error);if(c.title!=null)a.settings.title=c.title;n();p();
if(d.isFunction(a.settings.onLoad)==!0)a.settings.onLoad(a.me,b,f);H(!0);a.settings.veil&&I()}else a.settings.veil?a.dialog.hide():(a.me.html(a.settings.texts.loading),p(!0),H()),e.toLowerCase().lastIndexOf(".js")==e.length-3?(e=e.substr(0,e.length-3),require(e,function(c){if(c!=null){if(c.title)a.settings.title=c.title;c=c.data}if(E()!=!1){a.dialog.show();d.fn.sfDialog.resources[e]={url:e,data:c};var f=!1;c!=null?(K(c,a.load_url),f=!0):a.me.html(a.settings.texts.error);n();p();if(d.isFunction(a.settings.onLoad)==
!0)a.settings.onLoad(a.me,b,f);C({async:!0,noanim:!0,callback:function(){a.settings.veil&&I()}})}})):d.ajax({dataType:"text",url:e,success:function(c){if(E()!=!1){a.dialog.show();d.fn.sfDialog.resources[e]={url:e,data:c};K(c,a.load_url);n();p();if(d.isFunction(a.settings.onLoad)==!0)a.settings.onLoad(a.me,b,!0);C({async:!0,noanim:!0,callback:function(){a.settings.veil&&I()}})}},error:function(){if(E()!=!1){a.dialog.show();d.fn.sfDialog.resources[e]={url:e,data:null};a.me.html(a.settings.texts.error);
p();if(d.isFunction(a.settings.onLoad)==!0)a.settings.onLoad(a.me,b,!1);C({async:!0,noanim:!0})}}})}}function T(b){var c=d.extend(!0,{save:null},b);if(!(typeof c.save!="string"||c.save.length==0)){c=c.save;b.save=null;var e=d("input[type='radio'],input[type='checkbox'],select",g),f=[];d("input[type='radio']",g).each(function(a){a=d(e[a]);a.prop("checked")==!0&&f.push(a)});e.each(function(a){a=d(e[a]);if(a.is("input")==!0)a.prop("checked")==!1?a.removeAttr("checked"):a.attr("checked","checked");else if(a.is("select")==
!0){var b=a.prop("selectedIndex");a.children().removeAttr("selected");a.children().eq(b).attr("selected","selected")}});for(b=0;b<f.length;b++)b=f[b],b.attr("checked","checked");b=a.me.html().replace(/ selected=\"\"/g,"");b=b.replace(/ selected=\"\"/g,"");b={name:c,settings:d.extend(!0,{},a.settings),meId:a.me.attr("id"),html:b,title:a.me.attr("data-title"),styles:a.me.attr("style")};b.settings.save=null;b.settings.load=null;b.settings.restore=null;d.fn.sfDialog.saves[c]=b;d.fn.sfDialog.savesArr.push(b)}}
function R(b){var c=d.extend(!0,{restore:null},b);if(typeof c.restore!=="undefined"){var e=c.restore;typeof b!="undefined"&&typeof b.restore!="undefined"&&delete b.restore;var f;typeof c.restore==="string"?f=d.fn.sfDialog.saves[e]:e==!0&&d.fn.sfDialog.savesArr.length>0&&(f=d.fn.sfDialog.savesArr.pop());if(typeof f!="undefined"&&(a.settings=f.settings,a.me.empty().append(f.html).attr({style:f.styles,"data-title":f.title}),n(),p(),H(!0),d.isFunction(a.settings.onRestore)===!0))a.settings.onRestore(b)}}
function L(){return a.tabs==null?-1:a.tabs.sfTabs("getSelected")}function G(b){return a.tabs==null?void 0:a.tabs.sfTabs("select",b)}function V(b){a.mode==="wizard"&&(b="right");a.buttons.removeClass("sf-dialog-buttons-left sf-dialog-buttons-right");switch(b.toLowerCase()){case "left":a.settings.buttonAlign="left";a.buttons.addClass("sf-dialog-buttons-left");break;case "right":a.settings.buttonAlign="right";a.buttons.addClass("sf-dialog-buttons-right");break;default:a.settings.buttonAlign="center"}}
function H(b){function c(){var b={};if(a.settings.veil)b.top=a.settings.veil.sfDialog("getVeilTop"),b.left=a.settings.veil.sfDialog("getVeilLeft")+(a.settings.veil.sfDialog("getVeilWidth")-a.dialog.width())/2;return b}E()!=!1&&a.base.positioner({idealWidth:a.settings.veil?a.settings.veilWidthIdeal:a.settings.dialogWidthIdeal,widthMin:a.buttonsWidth+10,heightMin:!a.settings.veil?a.settings.dialogHeightMin:0,margin:d.fn.sfDialog.globals.dialogMargin,extraHeight:function(){return(a.settings.titleHidden==
!1?a.title.outerHeight(!0):0)+a.buttons.outerHeight(!0)+(a.footer?a.footer.outerHeight(!0):0)+(a.tabsHeight>0?a.tabsHeight:a.tabsHeight===0&&a.tabs!=null&&a.dialog.is(":visible")==!0?a.tabs_menu.outerHeight():0)},widthAdjustment:function(b){var c=a.me.children("div.sf-tabs-actv-content"),e=a.dialog.find("ul.sf-tabs-bborder, ul.sf-g-tabs"),f=b;if(e.length>0&&c.length>0){var g=e.outerWidth(!0)-e.width();e.children("li").each(function(){g+=d(this).outerWidth(!0)});f=g>c.width()?g:c.width()}c.length==
0&&(c=a.me.children("div:first"));c.length==1&&c.css("width").indexOf("px")>0&&(b=c.width()>f?c.width():f);return b}}).set({anchorAttachment:a.settings.anchorAttachment,disableAnimations:b,specialSizing:function(b){if(a.settings.veil){b.disableAnimations=!0;b.position.top=a.settings.veil.sfDialog("getVeilTop");var c=b.page.height-(b.position.top-b.page.top)-b.deltas.marginY;if(b.dimensions.height>c)b.dimensions.height=c,b.dimensions.innerHeight=b.dimensions.height-b.deltas.y-b.deltas.extraHeight}return b},
afterPositioning:a.settings.veil?c:null,onAfterPosition:function(){if(d.isFunction(a.settings.onAfterPosition))a.settings.onAfterPosition(a.me)},usePositioning:a.usePositioning===!0,containerOffset:a.settings.dialogOffset})}function ba(){C()}function I(){var b=a.dialog.height();parseInt(a.content.position().top);a.dialog.show().css({height:"10px",position:"absolute",overflow:"hidden"}).animate({height:b+"px"});a.content.css({position:"relative",top:"-"+b+"px"}).animate({top:"0px"},function(){a.content.css({position:"",
top:""})});a.settings.veil.sfDialog("setVeilDraggable",!1)}function ca(){a.dialog.animate({height:"0px"},function(){a.dialog.hide()});var b=a.dialog.height();a.content.css({position:"relative",top:"0px"}).animate({top:"-"+b+"px"},function(){a.content.css({position:"",top:""})});a.settings.veil.sfDialog("setVeilDraggable",!0)}function da(){a.me.sfDialog("close");return!1}function S(){y()}function U(b,c){d.isFunction(b)&&a.settings.draggable==!0&&typeof a.me.draggable!="undefined"&&a.dialog.bind("drag"+
(typeof c==="string"&&c.length>0?"."+c:""),b)}if(g.length==0)return g;a.logger=$sf.util.logger(g.attr("id"),"duel").log;if(b==="open"&&typeof e!=="undefined"&&(!e.hasOwnProperty("modal")||typeof a.settings==="undefined"))b=e;if(typeof b=="string")switch(b.toLowerCase()){case "isinitialized":return a.initialized;case "open":e=typeof e!=="undefined"?d.extend(!0,{fromMethod:!0},e):void 0;J(e);break;case "close":B();break;case "isopen":return E();case "toggle":Y(e);break;case "cancel":N();break;case "destroy":y();
break;case "enable":O();break;case "disable":P();break;case "save":T(e);break;case "preload":Z(e);break;case "load":Q(e);break;case "restore":R(e);break;case "isenabled":return a.isEnabled;case "getbutton":return s(e);case "setbutton":e.index<0||e.index>=a.settings.buttons.length||(a.settings.buttons[e.index]=e,p());break;case "getbuttons":return a.settings.buttons;case "setbuttons":h(e);break;case "isbuttondisabled":return u(e);case "disablebutton":t(e);break;case "enablebutton":o(e);break;case "istabdisabled":return a.tabs==
null?null:a.tabs.sfTabs("isdisabled",e);case "disabletab":a.tabs==null||a.tabs.sfTabs("disable",e);break;case "enabletab":a.tabs==null||a.tabs.sfTabs("enable",e);break;case "resize":C(e);break;case "getselectedtab":return L(e);case "selecttab":G(e);break;case "hidetab":a.tabs==null||a.tabs.sfTabs("hide",e);break;case "showtab":a.tabs==null||a.tabs.sfTabs("show",e);break;case "setbuttonalign":V(e);break;case "setondrag":U(e);break;case "setveildraggable":A(e);break;case "setattachment":a.settings.anchorAttachment=
e;C();break;case "getloadqs":return aa();case "getloadurl":return a.load_url;case "getveiltop":return b=a.content?a.content.offset().top:0,b;case "getveilleft":return b=a.dialog?a.dialog.offset().left:0,b;case "getveilwidth":return b=a.dialog?a.dialog.width():0,b;case "settings":return a.settings;default:k(e)}else k(b);return a.me}};return k.fn(k,e,j)};d.fn.sfDialog.instances={};d.fn.sfDialog.resources={};d.fn.sfDialog.saves={};d.fn.sfDialog.savesArr=[];d.fn.sfDialog.opens=0;d.fn.sfDialog.globals=
{dialogMargin:{x:40,y:20}};return d.fn.sfDialog}($sf.getjQuery())});
define("starfield/sf.alerts",["css!starfield/sf.core.css","jq!starfield/jquery.mod"],function(){return function(c){c.fn.sfAlert=function(f){var d=c(this);d.each(function(){var d=c(this),j=d.data("sf-alert-id");if(!j||j.length==0)j=Math.round(Math.random()*1E6),d.data("sf-alert-id",j);var g=c.fn.sfAlert.instances[j];if(g!=null)return g.me=d,g.fn(g,f);g=c.fn.sfAlert.instances[j]={me:c(this),init:!1,timer:null,fn:function(b,d){function a(){if(b.timer)window.clearTimeout(b.timer),b.timer=null}function e(a,
d){if(b.init==!1)return!1;var g=b.settings;if(c.isFunction(g.onClose)==!0&&g.onClose(b.me)==!1&&(typeof a=="undefined"||a!==!0))return!1;b.init=!1;if(b.timer)window.clearTimeout(b.timer),b.timer=null;b.me.fadeOut(function(){b.me.hide();b.me.attr("class")&&b.me.attr("class",b.me.attr("class").replace(/sf\-alert[a-z0-9_.-]*/ig,"").replace(/(^ +| +$)/g,"").replace(/ +/g," "));b.me.empty();if(c.isFunction(b.settings.onClosed))b.settings.onClosed();b.settings.destroyOnClose===!0&&f();c.isFunction(d)==
!0&&d()});return!1}function f(){e(!0);b.me.remove();return!0}var g=b.me;if(g.length==0)return g;b.settings=c.extend({autoCloseTimeout:0,style:null,message:null,destroyOnClose:null,hideClose:!1,onClose:null,onClosed:null},b.settings,d);if(b.settings.destroyOnClose===null)b.settings.destroyOnClose=g.parent().length==0;if(typeof d=="string")switch(d){case "close":return e(),g;case "destroy":return f(),g}g.children();var j=!b.init?g.html():"";b.init||g.empty();if(b.settings.message)j=b.settings.message;
else if(j.length>0)b.settings.message=j;b.init=!0;var q=g.children(".sf-alert-close:first");q.length==0&&(q=c('<a href="javascript: void(0);" onclick="return false;" class="sf-alert-close sf-icn sf-icn-close2"><span class="sf-offscrn">Close</span></a>'),q.bind("click",e),g.bind("mouseover",a),g.prepend(q));b.settings.hideClose==!0&&q.hide();var r=g.children(".sf-icn-alert:first");r.length==0&&(r=c("<div/>"),q.after(r));q=r.children("span:first");q.length==0&&(q=c('<span class="sf-offscrn"/>'),r.append(q));
g.attr("class",g.attr("class")?g.attr("class").replace(/sf\-alert[a-z0-9_.-]*/ig,"").replace(/ +/g," ")+" sf-alert":"sf-alert");r.attr("class","sf-icn-alert");var A=b.settings.style;A==null&&(A=g.attr("data-style"));switch(A){case "error":g.addClass("sf-alert-error");r.addClass("sf-icn-alert-error");q.text("error");break;case "warn":g.addClass("sf-alert-warning");r.addClass("sf-icn-alert-warning");q.text("warning");break;case "success":g.addClass("sf-alert-success");r.addClass("sf-icn-alert-success");
q.text("confirmation");break;default:g.addClass("sf-alert-info"),r.addClass("sf-icn-alert-info"),q.text("information")}q=g.children(".sf-alert-msg");q.length==0&&(q=c('<div class="sf-alert-msg"/>'),r.after(q));j&&q.html(j);g.hide().fadeIn();if(b.settings.autoCloseTimeout>0)b.timer=window.setTimeout(e,b.settings.autoCloseTimeout);return b.me}};return g.fn(g,f)});return d};c.fn.sfAlert.instances={};return c.fn.sfAlert}($sf.getjQuery())});
define("starfield/sf.msg.overlay",["css!starfield/sf.core.css","jq!starfield/jquery.mod","domReady!"],function(){return function(c){var f=c.fn.sfMsgOverlay=function(d){var e=c(this);e.each(function(){var e=c(this),g=e.data("sf-msgo-id");if(!g||g.length==0)g=Math.round(Math.random()*1E6),e.data("sf-msgo-id",g);var b=f.instances[g];if(b!=null)return b.me=e,b.fn(b,d);b=f.instances[g]={me:e,init:!1,fn:function(b,a){function d(){if(e.attr("data-unbound")!=="true"){var a,g;if(b.init==!1){b.init=!0;a=b.wrap=
c("<div class='sf-msg-overlay-wrap' />");g=b.overlay=c("<div class='sf-msg-overlay' />");a.append(g);b.pos=e.css("position");b.pos=="static"&&e.css("position","relative");if($sf.util.ua.ie&&$sf.util.ua.major<=6)b.height=e.css("height"),b.overflow=e.css("overflow");c(window).bind("resize",d);e.prepend(a)}else a=b.wrap,g=b.overlay;setTimeout(function(){var a=g;if($sf.util.ua.ie&&$sf.util.ua.major<=6){var b=e.height();e.css({height:b+"px",overflow:"hidden"})}a.html((f.style=="progress"?'<img src="{0}/sf.core/images/sf-spinner.gif" width="16" height="16" class="sf-msg-overlay-status" /> '.sfFormat($sf.require.img_root):
"")+f.message);b=a.innerHeight()/2*-1;a.css("margin-top",b+"px")},0)}}var e=b.me,f=b.settings=c.extend({style:"progress",message:null},b.settings,a);e.removeAttr("data-unbound");if(typeof f.message=="string")d();else if(e.attr("data-unbound","true"),b.init!=!1)b.init=!1,c(window).unbind("resize",d),b.wrap.remove(),b.pos=="static"&&e.css("position","static"),$sf.util.ua.ie&&$sf.util.ua.major<=6&&e.css({height:b.height,overflow:b.overflow});return b.me}};return b.fn(b,d)});return e};f.instances={};
return f}($sf.getjQuery())});
define("starfield/sf.i18n/duel",[],function(){var c={yes:"Yes",no:"No",ok:"OK",cancel:"Cancel",close:"Close",select:"Select",current:"Current",newStr:"New"};return{culture:"en",common:c,"sf.alerts":{},"sf.upload":{select:"Select Files",upload:"Start Upload",intro:"Select files to upload.",introWithDrop:"Select files to upload, or drop files here.",introMaxItems:"Maximum uploads reached.",statusPending:"{0} file(s) pending.",statusUploading:"{0} file(s) uploading...",statusFinished:"<strong>Finished!</strong> {0} file(s) uploaded with {1} error(s).",pending:"Pending",
finished:"Finished",uploading:"Uploading...",dd_info:"Drop files here to upload",dd_dest:"Destination",dd_limits:"Restrictions...",dd_cancel:"Cancel",cancel:"Are you sure you want to cancel all uploads?",maxSize:"Maximum size exceeded.",yes:"Yes",no:"No",error:"Error",retry:"Try again"},"sf.dialog":{title:"&lt;Untitled&gt;",button:"Button",stepOf:"Step {0} of {1}",error:"Woops! An error has occurred.",loading:"Loading, please wait...",wizardNext:"Next",wizardBack:"Back",wizardFinish:"Finish",wizardCancel:"Cancel"},
"sf.tipper":{more:"Show More",less:"Show Less"},"sf.growl":{closeAll:"close all"},"sf.share":{fbThanks:"Thank you for liking this page",fbAlso:"You can also like this page.",fbTitle:"Post {{domain}} to your Facebook wall",fbLikePage:"Like this page on Facebook:",twLoad:"Loading Tweet Box...",twDup:"Tweet duplicates are not allowed. Please change your message.",twErr:"There was an error posting your Tweet.",twOK:"Your Tweet was posted successsfully.",twUnavail:"Tweet posting is temporarily unavailable.<br/>Please try again later.",
twPost:"Post to Twitter:",twFollowPage:"Follow this page on Twitter:",gplusBSupport:"It appears Google Plus doesn't support your browser.",gpPost:"Post to Google Plus:",gpFollowPage:"Follow this page on Google:",checkSite:"Check out this site!",shareSite:"Share this site"},"sf.validator":{pwMatch:"Password matches",xToYCharsLong:"be {0}-{1} characters long",hasLower:"include a lower case letter",hasUpper:"include an upper case letter",hasSpecial:"include a special character ({0})",excludeChars:"not include these characters ({0})",
hasNum:"include a number",req:"is required",validEmail:"Valid email address",criteria:"Criteria:"},"sf.colorpicker":{newColor:c.newStr,currentColor:c.current,ok:c.select,cancel:c.cancel,advanced:"Advanced",basic:"Basic"},"sf.tourguide":{more:"Show More",less:"Show Less",newFeatures:"New Features",newFeature:"New Feature",hide:"Hide"},"sf.pagehelp":{pageHelp:"Page Help",showHelp:"Show Page Help",hideHelp:"Hide Page Help",quickA:"Quick answers for the current page",home:"Home"},"sf.datagrid":{filter:"Filter",
items:"Items",selected:"Selected",page:"Page",of:"of",display:"Display",none:"None",all:"All",actions:"Actions",loading:"Loading data...",noDataToDisplay:"No data to display.",noDataForPage:"No data retrieved for this page.",dataRetrivalError:"Problem loading data. Please try again later."},"sf.player":{relatedVid:"Related videos"},"sf.session":{title:"Security Logout",message:"To protect your account, we're going to log you out because of inactivity.<br /><br /><p>Click <strong>Stay Logged In</strong> to extend your session.</p>",
keepAlive:"Stay Logged In",logout:"Log out",timeLeft:"seconds to<br />automatic logout",attention:"ATTENTION"}}});define("starfield/sf.core.pkg",["foscss!starfield/sf.core.css"],function(){});
