define("starfield/sf.tipper",["i18n!starfield/sf.i18n/duel","css!starfield/sf.core.css","starfield/sf.util","jq!starfield/jquery.mod"],function(A){return function(d){function y(i,o){var j=i;j.is(".sf_tipper,.sf-tip")==!1&&(j=d(".sf_tipper,.sf-tip",i));j.each(function(){var c=d(this),i=c.attr("data-title");if(typeof i!="string"||i.length==0)i=c.attr("data-tipper-title");var f=c.attr("data-content");if(typeof f!="string"||f.length==0)f=c.attr("data-tipper-content");var g=c.attr("data-style");if(typeof g!=
"string"||g.length==0)g=c.attr("data-tipper-style");var j=c.attr("data-location");if(typeof j!="string"||j.length==0)j=c.attr("data-tipper-location");var w=c.attr("data-width");if(typeof w!="string"||w.length==0)w=c.attr("data-tipper-width");var t=c.attr("data-target");if(typeof t!="string"||t.length==0)t=c.attr("data-tipper-target");t=typeof t!="string"||t.length==0?void 0:d(t);c.sfTipper(o,{style:g,location:j,title:i,content:f,width:w,target:t,initOnly:!0})})}d.fn.sfTipper=function(i,o){var j=d.extend({wireup:!1},
i),c=d(this);if(j.wireup===!0)return delete i.wireup,y(c,i),c;var n=c.data("sf-tipper-id");if(!n||n.length==0)n=Math.round(Math.random()*1E6),c.data("sf-tipper-id",n);j=d.fn.sfTipper.instances[n];if(j!=null)return j.me=c,j.fn(j,i,o);j=d.fn.sfTipper.instances[n]={me:c,meId:n,init:!1,settings:null,fn:function(f,g,i){function j(){z||d("iframe",l.document).each(function(){this.contentWindow===q&&(z=d(this))});return z}function o(){var a=d(l).scrollLeft(),b=d(l).scrollTop();return{left:a,top:b,right:a+
d(l).width(),bottom:b+d(l).height()}}function x(){return b.style=="tooltip"?"tipper":b.style}function u(){b.resize=!0;h[b.style].positionIt(h[b.style].getElements(c))}function B(a){var e=d(a.target);b.resize=!0;h[b.style].positionIt(h[b.style].getElements(c));var m=e.offset().top,e=m+e.height(),f=c.offset().top;(f<=m||f>=e)&&v(a)}function C(a,e){var m=a.indexOf("<\!--more--\>");if(m>-1){var f=a.substring(0,m),m=a.substring(m+11),a=f+'<div class="sf-tipper-more" style="display:none;">'+m+'</div><div class="sf-tipper-morelink"><a href="javascript: void(0);" onclick="return false;">'+
b.showMoreText+"</a></div>";m.indexOf("sf-tourpoint-nav")>-1&&(f=d("<div>"+a+"</div>"),f.find(".sf-tourpoint-nav").insertAfter(f.find(".sf-tipper-morelink")),a=f.html())}e.html(a);e.find(".sf-tipper-morelink a").bind("click",function(){var a=d(this),f=e.find(".sf-tipper-more");f.length>0&&(f.is(":visible")?(f.hide(),a.text(b.showMoreText)):(f.show(),a.text(b.showLessText)),a=x(),h[a].positionIt(h[a].getElements(c)))})}function v(a){var e=!1;if(a&&a.target)if(a=d(a.target),a.is(".sf-tipper-close")===
!1&&a.closest(".sf-"+x()).length>0&&a.is("a")===!1)if(a.is(".sf-tourpoint-nav-item"))return!1;else if(a.parent(".sf-tourpoint-nav").length>0)e=!0;else return!1;else if(a.is("a")&&a.parent().is(".sf-tipper-morelink"))return!0;if(d.isFunction(b.onClose)==!0&&!b.onClose(c))return!1;p.fadeTipper(void 0,void 0,e);return!0}$sf.util.logger(n.toString(),"duel");var b=d.extend({style:"tooltip",title:"",content:"",location:"auto",close:!1,closeTippers:void 0,initOnly:!1,onClose:null,onOpen:null,onDisplay:null,
autoOpen:!1,context:self,displayContext:self,width:void 0,disableClose:!1,disableFade:!1,attachIcon:!0,wireup:!1,zIndex:null,suppress:!1,suppressTippers:void 0,resume:!1,resumeTippers:void 0,destroy:!1,destroyTippers:void 0,target:void 0,showMoreText:A["sf.tipper"].more,showLessText:A["sf.tipper"].less},f.settings,g,i);f.settings=b;f.defaultWidths={qt:180,tooltip:213,tourpoint:213,howl:400};var q=b.context,l=b.displayContext,z=null,h={tooltip:{build:function(){return h.tipbox.build("tipper")},getElements:function(a){return h.tipbox.getElements(a)},
positionIt:function(a){return h.tipbox.positionIt(a)}},tourpoint:{build:function(){return h.tipbox.build("tourpoint")},getElements:function(a){return h.tipbox.getElements(a)},positionIt:function(a){return h.tipbox.positionIt(a)}},tipbox:{build:function(a){var e=d(l.document.createElement("div")).data("sf-tipper",c.data("sf-tipper")).data("sf-tipper-target",c).attr("class","sf-"+a).attr("data-style",a);b.groupId&&e.attr("data-group",b.groupId);b.zIndex&&e.css("z-index",b.zIndex);f.outside=e;d("body:first",
l.document).append(e);e.data("OnResize",u);e.data("OnScroll",B);e.data("OnClose",v);var m=d("<div class='sf-tipper-close sf-icn-close2 sf-icn' />"),r=parseInt(b.width),r=isNaN(r)||r===0?f.defaultWidths[a]:r,r=d("<div class='sf-"+a+"-wrap' />").css("width",r+"px");f.master=r;b.disableClose==!1&&r.append(m);e.append(r);m=d("<div class='sf-"+a+"-body' />");r.append(m);if(a=="tourpoint"&&b.heading){var k=d("<div class='sf-"+a+"-titlebarheading' />");m.append(k);f.heading=k;k.html(b.heading)}else f.heading=
null;b.title?(k=d("<h6 class='sf-"+a+"-heading' />"),m.append(k),f.title=k,k.html(b.title)):f.title=null;if(b.content)k=d("<div class='sf-"+a+"-content' />"),m.append(k),f.content=k,C(b.content,k);m=d(document.createElement("div"));f.arrow=m;a==="howl"&&m.addClass("sf-"+a+"-arrow-wrap");e.append(m);return{container:e,masterContainer:r,arrowDiv:m}},getElements:function(){return{container:f.outside,masterContainer:f.master,arrowDiv:f.arrow}},positionIt:function(a){var e=typeof b.target==="undefined"?
c:b.target;e.position();e=e.offset();if(l!==q){var d=j().offset();e.left+=d.left;e.top+=d.top}var d=a.masterContainer.outerWidth(),f=a.masterContainer.outerHeight(),k=o(),g=b.location;b.location=="auto"&&(g=e.top+f+10<k.bottom?"bottom":"top",g+=e.left+d+25<k.right?"right":"left");var k=g.indexOf("left")>-1?-1:1,i=g.indexOf("top")>-1?-1:1,h=x();a.arrowDiv.attr("class","sf-"+h+"-ptr-"+g+" sf-"+h+"-ptr");a.masterContainer.css({"float":k<0?"left":"right"});a.container.css({left:(k<0?e.left-d-a.arrowDiv.width()-
2:e.left+c.outerWidth()+2)+"px",top:e.top+((i<0?f:0)+c.height()/2)*i+"px",width:d+a.arrowDiv.width()-1+"px"})}},qt:{buildContainer:function(){return h.bubble.build("qt")},getElements:function(a){return h.bubble.getElements(a)},load:function(a,b){return h.bubble.load("qt",a,b)},positionIt:function(a){return h.bubble.positionIt(a,"qt",b.location==="bottom"?"bottom":"top")}},howl:{buildContainer:function(){return h.bubble.build("howl")},getElements:function(a){return h.bubble.getElements(a)},load:function(a,
b){return h.bubble.load("howl",a,b)},build:function(a){var b=h.bubble.buildContainer("howl");b.data("sf-tipper",c.data("sf-tipper")).data("OnResize",u).data("OnClose",v);f.outside=b;h.bubble.load("howl",b,a);return{container:b,el:a}},positionIt:function(a){return h.bubble.positionIt(a,"howl",b.location==="top"?"top":"bottom")}},bubble:{buildContainer:function(a){var e=d("body > .sf-"+a+":first",l.document);e.length==0&&(e=d('<div class="sf-'+a+'"'+(b.zIndex?' style="position: absolute; z-index: '+
b.zIndex+'"':"")+' data-style="'+a+'"><span class="sf-'+a+'-content"></span><span class="sf-'+a+'-arrow-wrap"><span class="sf-'+a+'-arrow"></span></span></div>'),d("body:first",l.document).append(e),a=="howl"&&(a=d("<div class='sf-tipper-close sf-icn-close2 sf-icn' />"),b.disableClose==!1&&e.append(a)));return e},getElements:function(a){return{container:f.outside,el:a}},load:function(a,e,c){e.css({width:"auto",top:0,left:0});var g=c.attr("data-content")?c.attr("data-content"):b.content,k=parseInt(b.width),
i=!(isNaN(k)||k<=0),k=i?k:f.defaultWidths[a],h=d("<div>"+g+"</div>").css({"max-width":k,position:"absolute",padding:"0",margin:"0","font-family":"arial, verdana, helvetica, sans-serif","font-size":"11px"}).appendTo(document.body),j=h.width(),j=j>k?k:j;h.remove();e.find(".sf-"+a+"-content").html(g);a==="howl"&&(c=c.attr("data-title")?c.attr("data-title"):b.title===""?null:b.title,g=e.find(".sf-"+a+"-heading"),c?g.length<=0?d('<div class="sf-'+a+'-heading">'+c+"</div>").insertBefore(e.find(".sf-"+a+
"-content")):g.text(c):g.length>0&&g.remove());a=e.width();$sf.util.ua.ie&&$sf.util.ua.major<=6&&"maxWidth"in l.document.body.style?e.css({width:a}):e.css(a>k?{width:k,"max-width":k}:a<j&&i?{width:j,"max-width":j}:{width:a})},positionIt:function(a,e,c){function d(b){return{left:b.left,top:b.top,right:b.left+a.container.outerWidth(),bottom:b.top+a.container.outerHeight()}}var c=c!=="bottom"?"top":"bottom",f=c=="top"?"bottom":"top",g=c,i=typeof b.target!=="undefined"?b.target:a.el,h=(i.outerWidth()-
a.container.outerWidth())/2,n=i.offset();if(l!==q){var p=j().offset();n.left+=p.left;n.top+=p.top}var s={top:n.top-a.container.outerHeight()-5,bottom:n.top+i.outerHeight()},h={left:n.left+h,top:s[c]};a.container.css(h);p=function(a,b){var c=o(),e=d(b);return e.left<c.left?Math.abs(e.left-c.left):e.right>c.right?c.right-e.right:0}(i,h,n);i=function(b,i){var h=o(),j=d(i),l=c=="bottom"?-1:1;if(h=j[c]*l<h[c]*l)a.container[l==1?"addClass":"removeClass"]("sf-"+e+"-below");g=h?f:c;return h?s[f]:i.top}(i,
h,n);g=="bottom"?a.container.addClass("sf-"+e+"-below"):a.container.removeClass("sf-"+e+"-below");a.container.css({left:h.left+p+"px",top:i});(function(b){var c=a.container.find(".sf-"+e+"-arrow-wrap");c.css({left:a.container.width()/2-b+c.width()/2+"px"})})(p,h)}}},p={initTrigger:function(a){a.hasClass("sf-tipper-target")||a.addClass("sf-tipper-target").data("sf-tipper-style",b.style);b.groupId&&a.data("sf-tipper-group",b.groupId);(a.is("a")&&a.attr("href")=="#"||a.is("label")||a.parents("label").length>
0)&&a.bind("click.sfTipper",function(){return!1});var c=b.initOnly;if(c==!0)b.initOnly=!1;if(!a.data("sf-tipper")&&(a.data("sf-tipper",parseInt(Math.random()*1E6)),b.style=="tooltip"||b.style=="howl"||b.style=="tourpoint"))if(b.attachIcon==!0&&(a.bind("click.sfTipper dblclick.sfTipper",function(){if(d(":sf-tipper(target="+a.data("sf-tipper")+",open)").length<=0)if(a.data("inClick"))return!1;else a.data("inClick",!0),a.sfTipper(b),setTimeout(function(){a.removeData("inClick")},1E3);else return!1}),
b.style=="tooltip"&&a.addClass("sf-tip-ico")),!b.autoOpen)return!1;f.init=!0;return c==!0?!1:!0},execOpen:function(){return d.isFunction(b.onOpen)==!0&&b.onOpen(c)===!1?!1:!0},requestToReposition:function(){var a=b.reposition;delete f.settings.reposition;if(a==!0&&f.init)return onResize(),!1},requestToClose:function(a){var e=b.close;delete f.settings.close;var g=x(),g=d(".sf-"+g+":first",l.document);if(g.length>0){if(g.data("sf-tipper")==c.data("sf-tipper")){if(e==!0)return outsideMaster=g,p.fadeTipper(!1,
g,!0),!1;f.title&&f.title.html(b.title);f.content&&C(b.content,f.content);h[a].positionIt(h[a].getElements(g));return!1}if(e==!0)return!1;q.setTimeout(function(){c.sfTipper(b)},100);return!1}else if(e==!0)return!1;return!0},requestToCloseTippers:function(a){var c=b.closeTippers;typeof c!=="undefined"&&(c=d.extend({excludeMe:!1},c));delete f.settings.closeTippers;if(typeof c!=="undefined"){var g=c.excludeMe===!0,h=":sf-tipper("+(c.style&&c.style!=="not mine"?"style="+(c.style==="mine"?a:c.style)+",":
"")+"target,open)",i;for(i in d.fn.sfTipper.instances)if(d.fn.sfTipper.instances.hasOwnProperty(i)){var j=d.fn.sfTipper.instances[i],l=j.me.attr("data-style")==="qt"?h.replace(",open",""):h;j.me.is(l)&&(c.style==="not mine"&&j.me.is(":sf-tipper(target,style="+a+")")||(!g||!j.me.is(f.me))&&j.me.sfTipper({close:!0}))}return!1}return!0},requestToSuppressResumeDestroyQuickTips:function(){var a=typeof b.suppressTippers!=="undefined"?"suppress":typeof b.resumeTippers!=="undefined"?"resume":typeof b.destroyTippers!==
"undefined"?"destroy":null;if(a===null)return!0;var c=d.extend({excludeMe:!1},b[a+"Tippers"]);delete f.settings[a+"Tippers"];if(typeof c!=="undefined"){var g=c.excludeMe===!0,h;for(h in d.fn.sfTipper.instances)d.fn.sfTipper.instances.hasOwnProperty(h)&&d.fn.sfTipper.instances[h].me.each(function(){var b=d(this);if(b.is(":sf-tipper(style=qt,target)")&&(!g||!b.is(f.me))){var c={};c[a]=!0;b.sfTipper(c)}});return!1}return!0},fadeTipper:function(a,e,g){if(!f.fading){f.fading=!0;e=e?e:f.outside;d("body",
q.document).die("click",e.data("OnClose"));d("body",l.document).die("click",e.data("OnClose"));c.parentsUntil("body").unbind("scroll",e.data("OnScroll"));d(l).unbind("scroll",e.data("OnResize"));d(l).unbind("resize",e.data("OnResize"));q!=l&&(d(q).unbind("resize",e.data("OnResize")),d(q).unbind("scroll",e.data("OnResize")));var h=function(){f.fading=!1;e.remove()};a===!0||b.disableFade===!0?h():b.fadeToAnchor&&!g?e.animate({top:b.fadeToAnchor.offset().top,left:b.fadeToAnchor.offset().left,opacity:0},
{duration:500,queue:!1,complete:h}):e.fadeOut(300,h)}},display:function(){return d.isFunction(b.onDisplay)===!0&&b.onDisplay(c,h[b.style].getElements(c).container)===!1?!1:!0}};switch(b.style){case "qt":if(!p.requestToCloseTippers(b.style))return c;if(!p.requestToSuppressResumeDestroyQuickTips(b.style))return c;var y=b.resume;if(b.resume)b.suppress=!1,b.resume=!1;var s=h.bubble.buildContainer("qt");d.each(c,function(){var a=d(this);p.initTrigger(a);y===!0&&a.removeAttr("data-suppressed");b.close||
b.suppress||b.destroy?((b.suppress||b.destroy)&&a.unbind("mouseover.sfTipper mouseout.sfTipper"),b.suppress&&a.attr("data-suppressed",!0),b.destroy?(d(":sf-tipper(target,style=qt)").length===1?s.remove():s.hide(),a.removeClass("sf-tipper-target").removeData("sf-tipper"),delete d.fn.sfTipper.instances[n]):s.hide()):a.bind("mouseover.sfTipper",function(){b.suppress||(h.qt.load(s,a),h.qt.positionIt({el:a,container:s}),s.show())}).bind("mouseout.sfTipper",function(){s.hide()})});break;default:(g=p.requestToCloseTippers(b.style))&&
(g=p.requestToSuppressResumeDestroyQuickTips(b.style));if(!g)return c;if(f.init||b.autoOpen)if(g=p.requestToClose(b.style),!g)return c;g=p.initTrigger(c);if(!g)return c;g=p.execOpen();if(!g)return c;g=h[b.style].build(c);h[b.style].positionIt(g);d(l).bind("resize",u);d(l).bind("scroll",u);c.parentsUntil("body").bind("scroll",B);q!=l&&(d(q).bind("resize",u),d(q).bind("scroll",u));p.display();b.disableClose===!1&&q.setTimeout(function(){d("body",q.document).live("click",v);d("body",l.document).live("click",
v)},100);b.resize===!0||b.disableClose===!0?(delete b.resize,g.container.show()):g.container.hide().fadeIn(300)}}};return j.fn(j,i,o)};d.fn.sfTipper.instances={};d.extend(d.expr[":"],{"sf-tipper":function(i,o,j){i=d(i);o=j[3];if(!o||o=="")return i.is(".sf-tipper, .sf-howl, .sf-tourpoint, .sf-qt");var j=o.split(","),c=!1,n=!1,f=d.grep(j,function(c){return c!="target"});f.length<j.length?(j=f,c=i.is(".sf-tipper-target"),n=!0):c=i.is(".sf-tipper, .sf-howl, .sf-tourpoint, .sf-qt");if(c){c=j.length==0;
for(o=0;o<j.length;o++){f=j[o];if(n)switch(f){case "open":c=d(":sf-tipper(target="+i.data("sf-tipper")+"):visible").length>0;break;case "closed":c=d(":sf-tipper(target="+i.data("sf-tipper")+"):visible").length==0;break;default:if(g=f.split("="),g.length>1)switch(g[0]){case "style":c=i.data("sf-tipper-style");c=c===g[1];break;case "group":c=i.data("sf-tipper-group"),c=c===g[1]}else c=!1}else switch(f){case "open":c=i.is(":visible");break;case "closed":c=!i.is(":visible");break;default:var g=f.split("=");
if(g.length>1){if((f=g[1])&&f.length>0)switch(g[0]){case "style":c=i.attr("data-style");c=c===f;break;case "group":c=i.attr("data-group");c=c===f;break;case "target":g=(g=i.data("sf-tipper"))?g.toString():"nope",c=g.toString()===f}}else c=!1}if(c==!1)break}}return c}});return d.fn.sfTipper}($sf.getjQuery())});
